#Projeto 11 - SoulMatch

## Instalação e importação de LIBS

### Instalação

In [ ]:
!pip cache purge

WARNING: No matching packages
Files removed: 0

In [ ]:
#Firebase e Pyrabase
!pip install firebase-admin pyrebase

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: firebase-admin in /usr/local/lib/python3.10/dist-packages (5.3.0)
Collecting pyrebase
  Downloading Pyrebase-3.0.27-py3-none-any.whl (9.6 kB)
Requirement already satisfied: google-api-core[grpc]<3.0.0dev,>=1.22.1 in /usr/local/lib/python3.10/dist-packages (from firebase-admin) (2.11.0)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.10/dist-packages (from firebase-admin) (2.84.0)
Requirement already satisfied: google-cloud-storage>=1.37.1 in /usr/local/lib/python3.10/dist-packages (from firebase-admin) (2.8.0)
Requirement already satisfied: google-cloud-firestore>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from firebase-admin) (2.11.0)
Requirement already satisfied: cachecontrol>=0.12.6 in /usr/local/lib/python3.10/dist-packages (from firebase-admin) (0.12.11)
Collecting gcloud==0.17.0
  Downloading gcloud-0.17.0.tar.gz (458 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 458.0/458.0 kB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting oauth2client==3.0.0
  Downloading oauth2client-3.0.0.tar.gz (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.2/77.2 kB 9.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pycryptodome==3.4.3
  Downloading pycryptodome-3.4.3.tar.gz (6.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 27.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting requests==2.11.1
  Downloading requests-2.11.1-py2.py3-none-any.whl (514 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 514.8/514.8 kB 41.1 MB/s eta 0:00:00
Collecting python-jwt==2.0.1
  Downloading python_jwt-2.0.1-py2.py3-none-any.whl (8.8 kB)
Collecting requests-toolbelt==0.7.0
  Downloading requests_toolbelt-0.7.0-py2.py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.3/52.3 kB 6.4 MB/s eta 0:00:00
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from gcloud==0.17.0->pyrebase) (0.21.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.10/dist-packages (from gcloud==0.17.0->pyrebase) (1.59.0)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.10/dist-packages (from gcloud==0.17.0->pyrebase) (3.20.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from gcloud==0.17.0->pyrebase) (1.16.0)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.10/dist-packages (from oauth2client==3.0.0->pyrebase) (0.5.0)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.10/dist-packages (from oauth2client==3.0.0->pyrebase) (0.3.0)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from oauth2client==3.0.0->pyrebase) (4.9)
Collecting jws>=0.1.3
  Downloading jws-0.1.3.tar.gz (8.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: msgpack>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from cachecontrol>=0.12.6->firebase-admin) (1.0.5)
Collecting google-api-core[grpc]<3.0.0dev,>=1.22.1
  Downloading google_api_core-2.10.2-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.6/115.6 kB 15.0 MB/s eta 0:00:00
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin) (2.17.3)
  Downloading google_api_core-2.10.1-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.5/115.5 kB 14.1 MB/s eta 0:00:00
  Downloading google_api_core-2.10.0-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 15.4 MB/s eta 0:00:00
  Downloading google_api_core-2.9.0-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB 14.2 MB/s eta 0:00:00
  Downloading google_api_core-2.8.2-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 14.2 MB/s eta 0:00:00
  Downloading google_api_core-2.8.1-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.7/114.7 kB 13.2 MB/s eta 0:00:00
  Downloading google_api_core-2.8.0-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.7/114.7 kB 14.4 MB/s eta 0:00:00
  Downloading google_api_core-2.7.3-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 15.6 MB/s eta 0:00:00
  Downloading google_api_core-2.7.2-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 14.6 MB/s eta 0:00:00
  Downloading google_api_core-2.7.1-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.7/114.7 kB 14.4 MB/s eta 0:00:00
  Downloading google_api_core-2.7.0-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.7/114.7 kB 12.1 MB/s eta 0:00:00
  Downloading google_api_core-2.6.1-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 15.4 MB/s eta 0:00:00
  Downloading google_api_core-2.6.0-py2.py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 13.9 MB/s eta 0:00:00
  Downloading google_api_core-2.5.0-py2.py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.8/111.8 kB 14.5 MB/s eta 0:00:00
  Downloading google_api_core-2.4.0-py2.py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.7/111.7 kB 14.6 MB/s eta 0:00:00
  Downloading google_api_core-2.3.2-py2.py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.8/109.8 kB 10.3 MB/s eta 0:00:00
  Downloading google_api_core-2.3.0-py2.py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.8/109.8 kB 11.9 MB/s eta 0:00:00
  Downloading google_api_core-2.2.2-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 kB 11.3 MB/s eta 0:00:00
  Downloading google_api_core-2.2.1-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 10.4 MB/s eta 0:00:00
  Downloading google_api_core-2.2.0-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 11.2 MB/s eta 0:00:00
  Downloading google_api_core-2.1.1-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 8.4 MB/s eta 0:00:00
  Downloading google_api_core-2.1.0-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 9.8 MB/s eta 0:00:00
  Downloading google_api_core-2.0.1-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.5/92.5 kB 9.3 MB/s eta 0:00:00
  Downloading google_api_core-2.0.0-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.4/92.4 kB 10.0 MB/s eta 0:00:00
  Downloading google_api_core-1.34.0-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.2/120.2 kB 13.3 MB/s eta 0:00:00
  Downloading google_api_core-1.33.2-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.5/115.5 kB 12.9 MB/s eta 0:00:00
  Downloading google_api_core-1.33.1-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.5/115.5 kB 13.9 MB/s eta 0:00:00
  Downloading google_api_core-1.33.0-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.2/115.2 kB 13.3 MB/s eta 0:00:00
  Downloading google_api_core-1.32.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.6/93.6 kB 11.9 MB/s eta 0:00:00
  Downloading google_api_core-1.31.6-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 12.1 MB/s eta 0:00:00
  Downloading google_api_core-1.31.5-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 7.2 MB/s eta 0:00:00
  Downloading google_api_core-1.31.4-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 10.9 MB/s eta 0:00:00
  Downloading google_api_core-1.31.3-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 11.7 MB/s eta 0:00:00
  Downloading google_api_core-1.31.2-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 11.1 MB/s eta 0:00:00
  Downloading google_api_core-1.31.1-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 10.1 MB/s eta 0:00:00
  Downloading google_api_core-1.31.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 9.9 MB/s eta 0:00:00
  Downloading google_api_core-1.30.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.2/93.2 kB 10.2 MB/s eta 0:00:00
  Downloading google_api_core-1.29.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 10.6 MB/s eta 0:00:00
  Downloading google_api_core-1.28.0-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 kB 10.4 MB/s eta 0:00:00
  Downloading google_api_core-1.27.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.2/93.2 kB 10.6 MB/s eta 0:00:00
  Downloading google_api_core-1.26.3-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 10.3 MB/s eta 0:00:00
  Downloading google_api_core-1.26.2-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 kB 10.4 MB/s eta 0:00:00
  Downloading google_api_core-1.26.1-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 kB 10.5 MB/s eta 0:00:00
  Downloading google_api_core-1.26.0-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.9/92.9 kB 10.9 MB/s eta 0:00:00
  Downloading google_api_core-1.25.1-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 9.6 MB/s eta 0:00:00
  Downloading google_api_core-1.25.0-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 10.7 MB/s eta 0:00:00
  Downloading google_api_core-1.24.1-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 11.2 MB/s eta 0:00:00
  Downloading google_api_core-1.24.0-py2.py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 11.3 MB/s eta 0:00:00
  Downloading google_api_core-1.23.0-py2.py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 11.3 MB/s eta 0:00:00
  Downloading google_api_core-1.22.4-py2.py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 7.7 MB/s eta 0:00:00
  Downloading google_api_core-1.22.3-py2.py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 10.5 MB/s eta 0:00:00
  Downloading google_api_core-1.22.2-py2.py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 9.3 MB/s eta 0:00:00
  Downloading google_api_core-1.22.1-py2.py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.1/91.1 kB 9.9 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of cachecontrol to determine which version is compatible with other requirements. This could take a while.
Collecting cachecontrol>=0.12.6
  Downloading CacheControl-0.12.11-py2.py3-none-any.whl (21 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
  Downloading CacheControl-0.12.10-py2.py3-none-any.whl (20 kB)
  Downloading CacheControl-0.12.9-py2.py3-none-any.whl (23 kB)
  Downloading CacheControl-0.12.8-py2.py3-none-any.whl (23 kB)
  Downloading CacheControl-0.12.7-py2.py3-none-any.whl (23 kB)
  Downloading CacheControl-0.12.6-py2.py3-none-any.whl (19 kB)
INFO: pip is looking at multiple versions of requests-toolbelt to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of python-jwt to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycryptodome to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of oauth2client to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gcloud to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyrebase to determine which version is compatible with other requirements. This could take a while.
Collecting pyrebase
  Downloading Pyrebase-3.0.26-py3-none-any.whl (9.5 kB)
INFO: pip is looking at multiple versions of cachecontrol to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading Pyrebase-3.0.25-py3-none-any.whl (9.5 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading Pyrebase-3.0.24-py3-none-any.whl (9.6 kB)
  Downloading Pyrebase-3.0.23-py3-none-any.whl (9.5 kB)
  Downloading Pyrebase-3.0.22-py3-none-any.whl (9.2 kB)
  Downloading Pyrebase-3.0.21-py3-none-any.whl (9.2 kB)
  Downloading Pyrebase-3.0.18-py3-none-any.whl (7.0 kB)
Collecting sseclient
  Downloading sseclient-0.0.27.tar.gz (7.5 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from pyrebase) (2.27.1)
Collecting requests-toolbelt
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 5.0 MB/s eta 0:00:00
Collecting python-jwt
  Downloading python_jwt-4.0.0-py2.py3-none-any.whl (7.0 kB)
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.2/446.2 kB 33.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: oauth2client in /usr/local/lib/python3.10/dist-packages (from pyrebase) (4.1.3)
Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 27.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin) (1.48.2)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin) (1.54.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->pyrebase) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->pyrebase) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->pyrebase) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->pyrebase) (1.26.15)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client>=1.7.8->firebase-admin) (4.1.1)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client>=1.7.8->firebase-admin) (0.1.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-firestore>=2.1.0->firebase-admin) (1.22.2)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from google-cloud-firestore>=2.1.0->firebase-admin) (2.3.2)
Requirement already satisfied: google-resumable-media>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage>=1.37.1->firebase-admin) (2.5.0)
Collecting jwcrypto>=1.4.2
  Downloading jwcrypto-1.4.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.1/85.1 kB 7.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin) (5.3.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media>=2.3.2->google-cloud-storage>=1.37.1->firebase-admin) (1.5.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.10/dist-packages (from httplib2>=0.9.1->gcloud==0.17.0->pyrebase) (3.0.9)
Requirement already satisfied: cryptography>=2.3 in /usr/local/lib/python3.10/dist-packages (from jwcrypto>=1.4.2->python-jwt->pyrebase) (40.0.2)
Collecting deprecated
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=2.3->jwcrypto>=1.4.2->python-jwt->pyrebase) (1.15.1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from deprecated->jwcrypto>=1.4.2->python-jwt->pyrebase) (1.14.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=2.3->jwcrypto>=1.4.2->python-jwt->pyrebase) (2.21)
Building wheels for collected packages: gcloud, pycrypto, sseclient, jwcrypto
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602934 sha256=04255956d8daaf4a6b03d0c3833be808d567ea36a969a04900eb74e94a658150
  Stored in directory: /root/.cache/pip/wheels/7c/30/88/5017af921da3a33af785f0d0fd3e944b845bc62a445a2c2f69
  Building wheel for pycrypto (setup.py) ... done
  Created wheel for pycrypto: filename=pycrypto-2.6.1-cp310-cp310-linux_x86_64.whl size=499011 sha256=ecc8ecb3bf996280e4d08c40ecf00153a197d947d3bf2ba806aa904d31c42cad
  Stored in directory: /root/.cache/pip/wheels/e8/4b/5b/b10a6fc885057b6ff9fbd5691d7e700d0a9408f80b7e6f12e0
  Building wheel for sseclient (setup.py) ... done
  Created wheel for sseclient: filename=sseclient-0.0.27-py3-none-any.whl size=5584 sha256=207b8eb3651cc194de97a293c2c0b15f1785adb2b34fc04d06e4d980069b7944
  Stored in directory: /root/.cache/pip/wheels/60/57/0e/09b1264923280e935a34cc543b7f147f5df12490bd7a992f42
  Building wheel for jwcrypto (setup.py) ... done
  Created wheel for jwcrypto: filename=jwcrypto-1.4.2-py3-none-any.whl size=90487 sha256=ee15915a8ff97b3682bb0279b5925787dcd1adaf807586b016e79a44dd7024bc
  Stored in directory: /root/.cache/pip/wheels/f1/68/e6/e5116968e037c817be7a184ee8d195642694e719e7089a0fd3
Successfully built gcloud pycrypto sseclient jwcrypto
Installing collected packages: pycrypto, deprecated, sseclient, requests-toolbelt, jwcrypto, gcloud, python-jwt, pyrebase
Successfully installed deprecated-1.2.13 gcloud-0.18.3 jwcrypto-1.4.2 pycrypto-2.6.1 pyrebase-3.0.18 python-jwt-4.0.0 requests-toolbelt-1.0.0 sseclient-0.0.27

In [ ]:
#MongoDB
!pip install pymongo

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pymongo
  Downloading pymongo-4.3.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (492 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.9/492.9 kB 6.4 MB/s eta 0:00:00
Collecting dnspython<3.0.0,>=1.16.0
  Downloading dnspython-2.3.0-py3-none-any.whl (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.7/283.7 kB 28.4 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.3.0 pymongo-4.3.3

In [ ]:
#Google Cloud Storage
!pip install gcsfs

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting gcsfs
  Downloading gcsfs-2023.5.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: decorator>4.1.2 in /usr/local/lib/python3.10/dist-packages (from gcsfs) (4.4.2)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Downloading aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 11.5 MB/s eta 0:00:00
Requirement already satisfied: google-auth>=1.2 in /usr/local/lib/python3.10/dist-packages (from gcsfs) (2.17.3)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.10/dist-packages (from gcsfs) (2.8.0)
Collecting fsspec==2023.5.0
  Downloading fsspec-2023.5.0-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.1/160.1 kB 16.8 MB/s eta 0:00:00
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.10/dist-packages (from gcsfs) (1.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from gcsfs) (2.27.1)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 16.0 MB/s eta 0:00:00
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (23.1.0)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 12.4 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (2.0.12)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 19.6 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.2->gcsfs) (0.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.2->gcsfs) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.2->gcsfs) (4.9)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.2->gcsfs) (1.16.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib->gcsfs) (1.3.1)
Requirement already satisfied: google-resumable-media>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->gcsfs) (2.5.0)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->gcsfs) (2.3.2)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->gcsfs) (2.11.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->gcsfs) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->gcsfs) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->gcsfs) (1.26.15)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->gcsfs) (3.20.3)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->gcsfs) (1.59.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media>=2.3.2->google-cloud-storage->gcsfs) (1.5.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs) (3.2.2)
Installing collected packages: multidict, fsspec, frozenlist, async-timeout, yarl, aiosignal, aiohttp, gcsfs
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 frozenlist-1.3.3 fsspec-2023.5.0 gcsfs-2023.5.0 multidict-6.0.4 yarl-1.9.2

In [ ]:
# Instalação para o BigQuery
!pip install google-cloud-bigquery google-cloud-storage
!pip install google-auth google-auth-oauthlib google-auth-httplib2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.10/dist-packages (3.9.0)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.10/dist-packages (2.8.0)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (1.54.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (1.22.2)
Requirement already satisfied: packaging>=20.0.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (23.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.5.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.8.2)
Requirement already satisfied: requests<3.0.0dev,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.27.1)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.3.2)
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.11.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (3.20.3)
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.17.3)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (1.59.0)
Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (1.48.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (0.3.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage) (1.16.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery) (1.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2.0.12)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage) (0.5.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: google-auth in /usr/local/lib/python3.10/dist-packages (2.17.3)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.10/dist-packages (1.0.0)
Requirement already satisfied: google-auth-httplib2 in /usr/local/lib/python3.10/dist-packages (0.1.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from google-auth) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth) (0.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib) (1.3.1)
Requirement already satisfied: httplib2>=0.15.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-httplib2) (0.21.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.10/dist-packages (from httplib2>=0.15.0->google-auth-httplib2) (3.0.9)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth) (0.5.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.27.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.4)

In [ ]:
#Biblioteca para transformar texto Unicode em ASCII
!pip install unidecode

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting unidecode
  Downloading Unidecode-1.3.6-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 kB 3.5 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.6

### Importação

In [ ]:
import json
import numpy as np
import pandas as pd
import unidecode
import firebase_admin
from google.auth import credentials
from firebase_admin import credentials
from firebase_admin import firestore
from pandas.io.json import json_normalize
import os
import re
from datetime import datetime
import pymongo
from pymongo import MongoClient
from pandas import json_normalize
from pandas.io.json import json_normalize
from google.cloud import bigquery
from google.cloud import storage
from google.oauth2 import service_account
from google.colab import auth

##Conexão Firebase

In [ ]:
# Configuração do Firestore
cred = credentials.Certificate("/content/dashboards-b2b-ad1-firebase-adminsdk-5cg9w-a3a9db42b7.json")
firebase_admin.initialize_app(cred)

# Acesso ao banco de dados do Firestore
db = firestore.client()

##Conexão Google Cloud Storage (bucket)

In [ ]:
#CONFIGURANDO DA CHAVE DE SEGURANCA (Enviada com o projeto)
serviceAccount = "/content/versatile-cove-384013-7aa201d11265.json"
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = serviceAccount

In [ ]:
#Configurações Google Cloud Storage
client = storage.Client()
path = 'gs://proj11'

##Carregando database do Firebase no Colab

Identificando as Coleções

In [ ]:
# Listar todas as coleções do banco de dados
collections = db.collections()
for collection in collections:
    print(collection.id)

Estudantes
Turmas

###Criando dataframe bruto de "Turmas"

In [ ]:
turmas_ref = db.collection("Turmas")
turmas_docs = turmas_ref.get()

# Imprimir os dados de cada documento
turmas_lista = []
for item in turmas_docs:
  turmas_lista.append(item.to_dict())

#Transformando turmas_lista em df
df_turmas_bruto = pd.DataFrame(turmas_lista)
df_turmas = df_turmas_bruto.copy()

###Criando dataframe bruto de "Estudantes"

In [ ]:
estudantes_ref = db.collection("Estudantes")
estudantes_docs = estudantes_ref.get()

# Imprimir os dados de cada documento
estudantes_lista = []
for item in estudantes_docs:
  estudantes_lista.append(item.to_dict())

#Transformando estudantes_lista em df
df_estudantes = pd.DataFrame(estudantes_lista)

##Carregando dados brutos no MongoDB

In [ ]:
#Conector MongoDB Atlas
uri = "mongodb+srv://cluster0.jjkb9co.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority"
client = MongoClient(uri,tls=True,tlsCertificateKeyFile='/content/X509-cert-3926889476236238374.pem')             
db = client['soulcode']

In [ ]:
colecao = db['estudantes']

# Converta o DataFrame do pandas em um dicionário de Python
estudantes = df_estudantes.to_dict('records')

# Insira os registros na coleção do MongoDB usando o método insert_many()
colecao.insert_many(estudantes)

In [ ]:
colecao = db['turmas']

# Converta o DataFrame do pandas em uma lista de dicionários de Python
turmas = df_turmas_bruto.to_dict('records')

# Insira os registros na coleção do MongoDB usando o método insert_many()
colecao.insert_many(turmas)

##Carregamento de dados brutos no Bucket

In [ ]:
df_estudantes.to_csv('gs://proj11/brutos/estudantes.csv',index=False)

In [ ]:
df_turmas_bruto.to_csv('gs://proj11/brutos/turmas.csv',index=False)

## Pré-análise do `df_turmas_bruto`

###1. bootcampStatus

In [ ]:
df_turmas_bruto.groupby(['bootcampStatus'], dropna=False).size().sort_values(ascending=False)

bootcampStatus
Concluído       29
Em andamento     4
dtype: int64

###2. desistentes

In [ ]:
df_turmas_bruto.groupby(['desistentes'], dropna=False).size().sort_values(ascending=False)

desistentes
6.0     4
12.0    3
5.0     3
9.0     3
13.0    2
20.0    2
16.0    2
15.0    2
NaN     2
8.0     2
2.0     1
11.0    1
14.0    1
10.0    1
17.0    1
18.0    1
4.0     1
1.0     1
dtype: int64

###3. mediaTurma

In [ ]:
df_turmas_bruto.groupby(['mediaTurma'], dropna=False).size().sort_values(ascending=False)

mediaTurma
NaN       24
8.0000     2
6.6000     1
7.6875     1
7.7000     1
7.8000     1
7.9000     1
8.3000     1
8.6000     1
dtype: int64

###4. disciplinas

In [ ]:
df_turmas_bruto.groupby(['mediaTurma'], dropna=False).size().sort_values(ascending=False)

mediaTurma
NaN       24
8.0000     2
6.6000     1
7.6875     1
7.7000     1
7.8000     1
7.9000     1
8.3000     1
8.6000     1
dtype: int64

### 5. bootcampCodigo

In [ ]:
df_turmas_bruto.groupby(['bootcampCodigo'], dropna=False).size().sort_values(ascending=False)

bootcampCodigo
4HFs6bpe5QWfgBEtfpbT    1
eMz0vb5K5dngm2wUoUIr    1
xLRt9jNBT12FdUni1tXI    1
wobgaWWWgfZv2GNjVb6L    1
wRUu8b24JA9teTnMPKto    1
uyMEdf66N9WqSJ35XSP1    1
o958myCwsjrQB8cxJc1K    1
no9SFHd9Y39MDGFmZt8j    1
mKI0NenT4UUfZ758N3WD    1
lCWu2zPwrWCyIijGjS4c    1
koH17PebhftgjcWzxQFc    1
jHXYKk7zodgzbHQX0bZv    1
hzymD9j5KwP9r4Ae33t3    1
hx5dHDdRlX6q1LAysknt    1
gEqsxZBau69FlCUCIQ6W    1
eUiJfVtDc9A1YKftT38z    1
ZMvcHSfZH1t1WZLDx8Vs    1
6FFmCn0K9rpi4p7iLAMK    1
YhaiPrTxiFLS65fDfsJj    1
XeNHNAaEGqIkWSEsAjLP    1
UDHyPuSEWNLMvENjOro6    1
OvL1dam3Yy4IzlgP4TJm    1
Nl0qBrwZ4IoSc5OwpefU    1
JxMZHyh2I3RR2loFaG1p    1
JVH8fHm97DwTI07N1YNM    1
Ic5EWwr6MEMoGvSdkrR7    1
GDEAJXvFmdhHgnlrVsCt    1
CUZKZA6JtB8SUoPsCRVW    1
CEKdYcPHEBjSIvAMxO1F    1
8zcCz89t7r2s0RcPdkIB    1
7uVovxasalK3skKfgvTA    1
6rHhoKZq8BFvYPbWGd0H    1
yQbiG8kvfQxMUC7AXVAn    1
dtype: int64

###6. bootcampNome

In [ ]:
df_turmas_bruto.groupby(['bootcampNome'], dropna=False).size().sort_values(ascending=False)

bootcampNome
AD1     1
BC17    1
RN1     1
BC30    1
BC29    1
BC28    1
BC27    1
BC26    1
BC25    1
BC24    1
BC23    1
BC22    1
BC21    1
BC20    1
BC19    1
BC18    1
BC16    1
BC01    1
BC15    1
BC14    1
BC13    1
BC12    1
BC11    1
BC10    1
BC09    1
BC08    1
BC07    1
BC06    1
BC05    1
BC04    1
BC03    1
BC02    1
SF8     1
dtype: int64

###7. bootcampTipo

In [ ]:
df_turmas_bruto.groupby(['bootcampTipo'], dropna=False).size().sort_values(ascending=False)

bootcampTipo
Web Full Stack            11
Salesforce                 8
Engenharia de Dados        6
Martech                    4
Analista de Dados          1
Front-End e Mobile         1
Google Cloud Computing     1
ServiceNow                 1
dtype: int64

###8. disponiveis

In [ ]:
df_turmas_bruto.groupby(['disponiveis'], dropna=False).size().sort_values(ascending=False)

disponiveis
0.0     2
13.0    2
26.0    2
25.0    2
20.0    2
15.0    2
NaN     2
6.0     2
11.0    1
33.0    1
49.0    1
46.0    1
42.0    1
39.0    1
36.0    1
35.0    1
28.0    1
14.0    1
27.0    1
2.0     1
5.0     1
1.0     1
23.0    1
8.0     1
24.0    1
dtype: int64

In [ ]:
df_turmas_bruto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   professorUmNome        20 non-null     object
 1   ativo                  33 non-null     bool
 2   processo               31 non-null     float64
 3   disponiveis            31 non-null     float64
 4   mediaTurma             9 non-null      float64
 5   bootcampNome           33 non-null     object
 6   bootcampCodigo         33 non-null     object
 7   bootcampStatus         33 non-null     object
 8   bootcampTipo           33 non-null     object
 9   quantidadeAlunos       31 non-null     float64
 10  recuperacao            31 non-null     float64
 11  concluiram             9 non-null      float64
 12  dataInicio             33 non-null     object
 13  professorDoisId        20 non-null     object
 14  professorDoisNome      20 non-null     object
 15  fimContrato            16 non-null     object
 16  estudantes             33 non-null     object
 17  porcentagemEmpregados  4 non-null      float64
 18  desistentes            31 non-null     float64
 19  formados               31 non-null     float64
 20  naoEmpregaveis         31 non-null     float64
 21  empregados             31 non-null     float64
 22  porcentagemIndicacao   9 non-null      float64
 23  disciplinas            33 non-null     object
 24  professorUmId          20 non-null     object
 25  reciclagem             13 non-null     float64
 26  extensao               31 non-null     float64
 27  dataTermino            33 non-null     object
 28  dataDoBatch            13 non-null     object
 29  cluster                31 non-null     float64
 30  idProfessores          22 non-null     object
 31  professores            22 non-null     object
 32  key                    8 non-null      object
dtypes: bool(1), float64(15), object(17)
memory usage: 8.4+ KB

###9. dataInicio

In [ ]:
df_turmas_bruto.groupby(['dataInicio'], dropna=False).size().sort_values(ascending=False)

dataInicio
2023-02-13    3
2022-04-04    2
2022-10-17    2
2021-12-01    2
2022-12-05    1
2022-11-16    1
2022-09-14    1
2022-08-29    1
2022-07-11    1
2022-06-27    1
2022-06-06    1
2022-05-30    1
2022-05-23    1
2022-05-09    1
2021-01-31    1
2021-02-03    1
2022-03-07    1
2022-01-31    1
2022-01-17    1
2021-11-16    1
2021-10-25    1
2021-09-20    1
2021-08-30    1
2021-07-19    1
2021-06-14    1
2021-05-31    1
2021-03-03    1
2022-03-28    1
dtype: int64

###10. empregados

In [ ]:
df_turmas_bruto.groupby(['empregados'], dropna=False).size().sort_values(ascending=False)

empregados
0.0     6
11.0    3
6.0     3
26.0    2
2.0     2
NaN     2
8.0     2
10.0    1
12.0    1
19.0    1
7.0     1
24.0    1
25.0    1
5.0     1
27.0    1
28.0    1
31.0    1
34.0    1
39.0    1
23.0    1
dtype: int64

In [ ]:
df_turmas_bruto["empregados"].fillna(-1, inplace=True)

In [ ]:
df_turmas_bruto['empregados'] = df_turmas_bruto["empregados"].astype('int')
display(df_turmas_bruto['empregados'])

0     39
1     31
2     11
3      8
4     26
5     12
6      2
7      0
8     27
9      6
10     7
11    19
12     6
13    11
14    26
15    10
16    23
17     5
18     0
19    11
20    24
21    25
22     0
23    28
24    34
25     2
26     8
27     6
28    -1
29    -1
30     0
31     0
32     0
Name: empregados, dtype: int64

In [ ]:
df_turmas_bruto.loc[df_turmas_bruto.empregados == -1,['empregados']] = np.NaN

In [ ]:
display(df_turmas_bruto['empregados'])

0     39.0
1     31.0
2     11.0
3      8.0
4     26.0
5     12.0
6      2.0
7      0.0
8     27.0
9      6.0
10     7.0
11    19.0
12     6.0
13    11.0
14    26.0
15    10.0
16    23.0
17     5.0
18     0.0
19    11.0
20    24.0
21    25.0
22     0.0
23    28.0
24    34.0
25     2.0
26     8.0
27     6.0
28     NaN
29     NaN
30     0.0
31     0.0
32     0.0
Name: empregados, dtype: float64

###11. fimContrato

In [ ]:
df_turmas_bruto.groupby(['fimContrato'], dropna=False).size().sort_values(ascending=False)

fimContrato
NaN           17
2021-08-29     2
2022-04-28     2
2022-05-26     2
2021-10-07     1
2021-11-10     1
2021-12-30     1
2022-02-17     1
2022-03-03     1
2022-06-16     1
2022-07-14     1
2022-07-28     1
2022-08-29     1
2022-09-19     1
dtype: int64

###12. dataTermino

In [ ]:
df_turmas_bruto.groupby(['dataTermino'], dropna=False).size().sort_values(ascending=False)

dataTermino
2023-05-18    2
2023-01-20    2
2022-01-28    2
2022-02-25    2
2021-05-31    1
2022-08-16    1
2023-03-17    1
2023-02-17    1
2023-01-16    1
2022-11-25    1
2022-10-03    1
2022-09-28    1
2022-09-19    1
2022-08-30    1
2022-08-23    1
2022-06-28    1
2022-07-29    1
2021-07-09    1
2022-06-21    1
2022-05-31    1
2022-05-20    1
2022-04-29    1
2022-04-15    1
2022-03-18    1
2021-12-03    1
2021-11-19    1
2021-10-01    1
2021-08-12    1
2023-05-30    1
dtype: int64

###13. cluster

In [ ]:
df_turmas_bruto.groupby(['cluster'], dropna=False).size().sort_values(ascending=False)

cluster
0.0     21
1.0      5
2.0      2
NaN      2
3.0      1
4.0      1
14.0     1
dtype: int64

In [ ]:
df_turmas_bruto['cluster']

0      0.0
1      0.0
2      1.0
3      2.0
4      0.0
5      1.0
6      0.0
7     14.0
8      0.0
9      2.0
10     0.0
11     0.0
12     0.0
13     1.0
14     0.0
15     0.0
16     0.0
17     0.0
18     0.0
19     0.0
20     0.0
21     0.0
22     4.0
23     0.0
24     0.0
25     0.0
26     0.0
27     1.0
28     NaN
29     NaN
30     3.0
31     0.0
32     1.0
Name: cluster, dtype: float64

###14. quantidadeAlunos

In [ ]:
df_turmas_bruto.groupby(['quantidadeAlunos'], dropna=False).size().sort_values(ascending=False)

quantidadeAlunos
52.0    3
55.0    3
50.0    2
57.0    2
53.0    2
28.0    2
40.0    2
NaN     2
48.0    1
43.0    1
51.0    1
30.0    1
42.0    1
54.0    1
47.0    1
56.0    1
39.0    1
58.0    1
62.0    1
63.0    1
68.0    1
71.0    1
45.0    1
dtype: int64

###15. recuperacao

In [ ]:
df_turmas_bruto.groupby(['recuperacao'], dropna=False).size().sort_values(ascending=False)

recuperacao
0.0     28
NaN      2
1.0      1
6.0      1
13.0     1
dtype: int64

###16. extensao

In [ ]:
df_turmas_bruto.groupby(['extensao'], dropna=False).size().sort_values(ascending=False)

extensao
0.0    31
NaN     2
dtype: int64

###17. ativo

In [ ]:
df_turmas_bruto.groupby(['ativo'], dropna=False).size().sort_values(ascending=False)

ativo
False    29
True      4
dtype: int64

###18. formados

In [ ]:
df_turmas_bruto.groupby(['formados'], dropna=False).size().sort_values(ascending=False)

formados
33.0    3
43.0    3
27.0    3
31.0    3
39.0    2
50.0    2
37.0    2
NaN     2
29.0    2
34.0    1
20.0    1
40.0    1
42.0    1
25.0    1
44.0    1
45.0    1
49.0    1
24.0    1
59.0    1
0.0     1
dtype: int64

###19. naoEmpregaveis

In [ ]:
df_turmas_bruto.groupby(['naoEmpregaveis'], dropna=False).size().sort_values(ascending=False)

naoEmpregaveis
14.0    3
8.0     3
13.0    2
24.0    2
21.0    2
16.0    2
15.0    2
NaN     2
11.0    2
10.0    2
9.0     2
5.0     2
12.0    1
4.0     1
18.0    1
19.0    1
6.0     1
22.0    1
1.0     1
dtype: int64

In [ ]:
df_turmas_bruto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   professorUmNome        20 non-null     object
 1   ativo                  33 non-null     bool
 2   processo               31 non-null     float64
 3   disponiveis            31 non-null     float64
 4   mediaTurma             9 non-null      float64
 5   bootcampNome           33 non-null     object
 6   bootcampCodigo         33 non-null     object
 7   bootcampStatus         33 non-null     object
 8   bootcampTipo           33 non-null     object
 9   quantidadeAlunos       31 non-null     float64
 10  recuperacao            31 non-null     float64
 11  concluiram             9 non-null      float64
 12  dataInicio             33 non-null     object
 13  professorDoisId        20 non-null     object
 14  professorDoisNome      20 non-null     object
 15  fimContrato            16 non-null     object
 16  estudantes             33 non-null     object
 17  porcentagemEmpregados  4 non-null      float64
 18  desistentes            31 non-null     float64
 19  formados               31 non-null     float64
 20  naoEmpregaveis         31 non-null     float64
 21  empregados             31 non-null     float64
 22  porcentagemIndicacao   9 non-null      float64
 23  disciplinas            33 non-null     object
 24  professorUmId          20 non-null     object
 25  reciclagem             13 non-null     float64
 26  extensao               31 non-null     float64
 27  dataTermino            33 non-null     object
 28  dataDoBatch            13 non-null     object
 29  cluster                31 non-null     float64
 30  idProfessores          22 non-null     object
 31  professores            22 non-null     object
 32  key                    8 non-null      object
dtypes: bool(1), float64(15), object(17)
memory usage: 8.4+ KB

## Convertendo as colunas com dados possíveis de ajustes em `df_turmas_bruto`

In [ ]:
# Convertendo vazios e NA em NaN
df_turmas_bruto.replace([pd.NA,""],np.NaN,inplace=True)
df_turmas_bruto['fimContrato'] = pd.to_datetime(df_turmas_bruto['fimContrato'])

In [ ]:
df_turmas_bruto['bootcampTipo'] = df_turmas_bruto['bootcampTipo'].apply(lambda x: x.upper())
df_turmas_bruto['bootcampStatus'] = df_turmas_bruto['bootcampStatus'].apply(lambda x: x.upper())
df_turmas_bruto["professorUmNome"] = df_turmas_bruto["professorUmNome"].fillna('')
df_turmas_bruto["professorUmNome"] = df_turmas_bruto['professorUmNome'].apply(lambda x: x.upper())
df_turmas_bruto["professorUmNome"] = df_turmas_bruto["professorUmNome"].replace('', np.nan)
df_turmas_bruto["professorDoisNome"] = df_turmas_bruto["professorDoisNome"].fillna('')
df_turmas_bruto["professorDoisNome"] = df_turmas_bruto['professorDoisNome'].apply(lambda x: x.upper())
df_turmas_bruto["professorDoisNome"] = df_turmas_bruto["professorDoisNome"].replace('', np.nan)

Cópia de Segurança

In [ ]:
df_turmas_bkp = df_turmas_bruto.copy()

In [ ]:
df_turmas_bruto

,professorUmNome,ativo,processo,disponiveis,mediaTurma,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,quantidadeAlunos,...,disciplinas,professorUmId,reciclagem,extensao,dataTermino,dataDoBatch,cluster,idProfessores,professores,key
0,SAYURE VIEIRA DE PAIVA,False,0.0,6.0,8.0000,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,55.0,...,"[{'nome': 'HTML/CSS'}, {'nome': 'JAVASCRIPT'},...",l52ed8NxK0MQ9I8Tidiy3g0N0N12,27.0,0.0,2021-11-19,2022-02-21T19:27:29.068Z,0.0,NaN,NaN,NaN
1,BISMARK WILLIAM GOMES DE ARAUJO,False,0.0,13.0,7.7000,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,53.0,...,"[{'nome': 'INFRA'}, {'nome': 'PYTHON'}, {'nome...",4w6ztCDqtZRT2gD35i59CupCyXr2,15.0,0.0,2021-12-03,2022-02-21T19:27:29.068Z,0.0,NaN,NaN,NaN
2,TATIANA DIAS CHIACCHIO,False,1.0,25.0,NaN,BC13,6rHhoKZq8BFvYPbWGd0H,CONCLUÍDO,WEB FULL STACK,52.0,...,"[{'nome': 'HTML/CSS/BOOTSTRAP/JAVASCRIPT'}, {'...",djGodEEa8mZGArh4lm3gD30pCeg2,0.0,0.0,2022-05-20,2022-02-18T17:42:54.050Z,1.0,"[djGodEEa8mZGArh4lm3gD30pCeg2, yFtcYHIWdZg0ktg...","[{'nome': 'Tatiana Dias Chiacchio', 'id': 'djG...",NaN
3,NaN,False,1.0,28.0,NaN,BC21,7uVovxasalK3skKfgvTA,CONCLUÍDO,SALESFORCE,58.0,...,"[{'dataTermino': '2022-07-05', 'dataInicio': '...",NaN,NaN,0.0,2022-08-23,NaN,2.0,"[vFwIn8cbokc8eTpUt9QNbxP1hVe2, uUS6yngVC0egyUL...","[{'id': 'vFwIn8cbokc8eTpUt9QNbxP1hVe2', 'nome'...",NaN
4,FILIPE SANTANA DE OLIVEIRA,False,0.0,6.0,8.0000,BC03,8zcCz89t7r2s0RcPdkIB,CONCLUÍDO,FRONT-END E MOBILE,40.0,...,"[{'nome': 'HTML'}, {'nome': 'CSS'}, {'nome': '...",uUS6yngVC0egyULQrKtY6lsksqf1,1.0,0.0,2021-10-01,2022-02-21T19:27:29.068Z,0.0,NaN,NaN,NaN
5,FILIPE SANTANA DE OLIVEIRA,False,0.0,11.0,NaN,BC15,CEKdYcPHEBjSIvAMxO1F,CONCLUÍDO,SALESFORCE,28.0,...,"[{'dataTermino': '2022-03-22', 'nome': 'SALESF...",uUS6yngVC0egyULQrKtY6lsksqf1,NaN,0.0,2022-05-31,NaN,1.0,"[uUS6yngVC0egyULQrKtY6lsksqf1, vFwIn8cbokc8eTp...","[{'id': 'uUS6yngVC0egyULQrKtY6lsksqf1', 'nome'...",NaN
6,NaN,False,1.0,27.0,NaN,BC22,CUZKZA6JtB8SUoPsCRVW,CONCLUÍDO,WEB FULL STACK,55.0,...,"[{'dataInicio': '2022-06-29', 'dataTermino': '...",NaN,NaN,0.0,2022-09-28,NaN,0.0,"[AlK9beQkH3Xkzu92NED9aNF9yIj2, jR4MN2vPlybXYgG...","[{'id': 'AlK9beQkH3Xkzu92NED9aNF9yIj2', 'nome'...",NaN
7,NaN,False,3.0,42.0,NaN,BC26,GDEAJXvFmdhHgnlrVsCt,CONCLUÍDO,ENGENHARIA DE DADOS,68.0,...,"[{'dataInicio': '2023-01-09', 'nome': 'PROJETO...",NaN,NaN,0.0,2023-01-20,NaN,14.0,"[4nGZmWjPQ2TUoQfWWSi1bThad2O2, 4w6ztCDqtZRT2gD...","[{'nome': 'Igor Gondim Soares de Lemos', 'id':...",GDEAJXvFmdhHgnlrVsCt
8,SAYURE VIEIRA DE PAIVA,False,0.0,0.0,8.6000,BC02,Ic5EWwr6MEMoGvSdkrR7,CONCLUÍDO,WEB FULL STACK,28.0,...,"[{'nome': 'CLASSROOM'}, {'nome': 'HTML'}, {'no...",l52ed8NxK0MQ9I8Tidiy3g0N0N12,1.0,0.0,2021-07-09,2022-02-21T19:27:29.068Z,0.0,"[l52ed8NxK0MQ9I8Tidiy3g0N0N12, szR0aJ3FA4c0tYY...","[{'nome': 'SAYURE VIEIRA DE PAIVA', 'id': 'l52...",NaN
9,CAMILA VIDERES DE OLIVEIRA,False,0.0,13.0,NaN,BC19,JVH8fHm97DwTI07N1YNM,CONCLUÍDO,MARTECH,42.0,...,"[{'nome': 'PROJETO FINAL', 'dataTermino': '202...",84CEVPFx9fgl2WuOjKd2wcgwKuJ3,NaN,0.0,2022-08-16,NaN,2.0,"[84CEVPFx9fgl2WuOjKd2wcgwKuJ3, NtfUjHMWU8YgYi6...","[{'nome': 'Camila Videres de Oliveira', 'id': ...",NaN
10,NaN,False,1.0,33.0,NaN,BC23,JxMZHyh2I3RR2loFaG1p,CONCLUÍDO,ENGENHARIA DE DADOS,55.0,...,"[{'dataTermino': '2022-09-19', 'dataInicio': '...",NaN,NaN,0.0,2022-09-19,NaN,0.0,"[4nGZmWjPQ2TUoQfWWSi1bThad2O2, 4w6ztCDqtZRT2gD...","[{'nome': 'Igor Gondim Soares de Lemos', 'id':...",NaN
11,TATIANA CHIACCHIO,False,0.0,20.0,7.6875,BC07,Nl0qBrwZ4IoSc5OwpefU,CONCLUÍDO,WEB FULL STACK,45.0,...,"[{'nome': 'HTML'}, {'nome': 'CSS'}, {'nome': '...",djGodEEa8mZGArh4lm3gD30pCeg2,34.0,0.0,2022-01-28,2022-02-21T19:27:29.068Z,0.0,NaN,NaN,NaN
12,NaN,False,2.0,36.0,NaN,BC24,OvL1dam3Yy4IzlgP4TJm,CONCLUÍDO,SALESFORCE,52.0,...,"[{'nome': 'SALESFORCE DEV I'}, {'nome': 'SALES...",NaN,NaN,0.0,2022-10-03,NaN,0.0,"[4Mx2wYepkeSupFAaL0zUONlN0PG3, I0U8pfCzh7ctvk2...","[{'nome': 'Luiz Prandini', 'id': '4Mx2wYepkeSu...",NaN
13,ADRIANO GOMES DA SILVA,False,0.0,20.0,NaN,BC17,UDHyPuSEWNLMvENjOro6,CONCLUÍDO,ENGENHARIA DE DADOS,54.0,...,"[{'dataInicio': '2022-04-19', 'dataTermino': '...",AlK9beQkH3Xkzu92NED9aNF9yIj2,NaN,0.0,2022-06-21,NaN,1.0,"[AlK9beQkH3Xkzu92NED9aNF9yIj2, 4nGZmWjPQ2TUoQf...","[{'nome': 'Adriano Gomes da Silva ', 'id': 'Al...",NaN
14,FILIPE SANTANA DE OLIVEIRA,False,0.0,5.0,NaN,BC11,XeNHNAaEGqIkWSEsAjLP,CONCLUÍDO,SALESFORCE,47.0,...,"[{'nome': 'ADM'}, {'nome': 'APEX1'}, {'nome': ...",uUS6yngVC0egyULQrKtY6lsksqf1,0.0,0.0,2022-02-25,2022-02-21T17:44:57.970Z,0.0,NaN,NaN,NaN
15,DIOGO ARRUDA SOARES,False,1.0,15.0,NaN,BC14,YhaiPrTxiFLS65fDfsJj,CONCLUÍDO,MARTECH,39.0,...,"[{'nome': 'MÍDIAS & CANAIS DIGITAIS'}, {'nome'...",NtfUjHMWU8YgYi6ICq87e13Qd4z2,0.0,0.0,2022-04-29,2022-02-18T17:42:54.050Z,0.0,"[NtfUjHMWU8YgYi6ICq87e13Qd4z2, 84CEVPFx9fgl2Wu...","[{'nome': 'Diogo Arruda Soares', 'id': 'NtfUjH...",NaN
16,JOSE ALMIR DE SOUZA GOMES JUNIOR,False,1.0,15.0,7.8000,BC09,ZMvcHSfZH1t1WZLDx8Vs,CONCLUÍDO,WEB FULL STACK,50.0,...,"[{'nome': 'HTML/CSS'}, {'nome': 'JAVASCRIPT'},...",FiqEWj5gfBZrOee7RXdUMgWBIxq1,0.0,0.0,2022-03-18,2022-02-21T17:44:57.970Z,0.0,NaN,NaN,NaN
17,JOSÉ RENATO DE AQUINO PEREIRA FILHO,False,0.0,26.0,NaN,BC20,eMz0vb5K5dngm2wUoUIr,CONCLUÍDO,WEB FULL STACK,51.0,...,"[{'dataTermino': '2022-06-22', 'dataInicio': '...",yFtcYHIWdZg0ktgIEas9o5Ift9M2,NaN,0.0,2022-08-30,NaN,0.0,"[yFtcYHIWdZg0ktgIEas9o5Ift9M2, FiqEWj5gfBZrOee...","[{'id': 'yFtcYHIWdZg0ktgIEas9o5Ift9M2', 'nome'...",NaN
18,NaN,False,0.0,39.0,NaN,BC29,eUiJfVtDc9A1YKftT38z,CONCLUÍDO,MARTECH,63.0,...,"[{'dataInicio': '2022-09-06', 'dataTermino': '...",NaN,NaN,0.0,2022-11-25,NaN,0.0,"[84CEVPFx9fgl2WuOjKd2wcgwKuJ3, i8vU3AsSqZRRam3...","[{'nome': 'Camila Videres de Oliveira', 'id': ...",eUiJfVtDc9A1YKftT38z
19,JOSÉ ALMIR DE SOUZA GOMES JÚNIOR,False,2.0,23.0,NaN,BC18,gEqsxZBau69FlCUCIQ6W,CONCLUÍDO,WEB FULL STACK,57.0,...,"[{'dataInicio': '2022-04-26', 'nome': 'ANGULAR...",FiqEWj5gfBZrOee7RXdUMgWBIxq1,NaN,0.0,2022-07-29,NaN,0.0,"[FiqEWj5gfBZrOee7RXdUMgWBIxq1, Irns3isTvnZNvBU...","[{'id': 'FiqEWj5gfBZrOee7RXdUMgWBIxq1', 'nome'...",NaN
20,BISMARK WILLIAM GOMES DE ARAUJO,False,0.0,1.0,8.3000,BC01,hx5dHDdRlX6q1LAysknt,CONCLUÍDO,WEB FULL STACK,30.0,...,"[{'nome': 'HTML/CSS'}, {'nome': 'JAVASCRIPT'},...",4w6ztCDqtZRT2gD35i59CupCyXr2,2.0,0.0,2021-05-31,2022-02-21T19:27:29.068Z,0.0,NaN,NaN,NaN
21,BISMARK WILLIAM GOMES DE ARAUJO,False,0.0,2.0,6.6000,BC04,hzymD9j5KwP9r4Ae33t3,CONCLUÍDO,GOOGLE CLOUD COMPUTING,40.0,...,"[{'nome': 'CLOUD1'}, {'nome': 'CLOUD2'}, {'nom...",4w6ztCDqtZRT2gD35i59CupCyXr2,0.0,0.0,2021-08-12,2022-02-21T19:27:29.068Z,0.0,NaN,NaN,NaN
22,NaN,False,0.0,25.0,NaN,BC27,jHXYKk7zodgzbHQX0bZv,CONCLUÍDO,SERVICENOW,43.0,...,"[{'dataInicio': '2022-11-16', 'nome': 'HTML, C...",NaN,NaN,0.0,2023-02-17,NaN,4.0,"[AlK9beQkH3Xkzu92NED9aNF9yIj2, JCBRD08dIthrJ6L...","[{'nome': 'Adriano Gomes da Silva ', 'id': 'Al...",jHXYKk7zodgzbHQX0bZv
23,ADRIANO GOMES,False,0.0,14.0,7.9000,BC08,koH17PebhftgjcWzxQFc,CONCLUÍDO,ENGENHARIA DE DADOS,52.0,...,"[{'nome': 'PYTHON'}, {'nome': 'PYSPARK'}, {'no...",AlK9beQkH3Xkzu92NED9aNF9yIj2,0.0,0.0,2022-01-28,2022-02-21T19:27:29.068Z,0.0,NaN,NaN,NaN
24,FILIPE SANTANA DE OLIVEIRA,False,0.0,8.0,NaN,BC10,lCWu2zPwrWCyIijGjS4c,CONCLUÍDO,SALESFORCE,57.0,...,"[{'nome': 'ADM'}, {'nome': 'APEX1'}, {'nome': ...",uUS6yngVC0egyULQrKtY6lsksqf1,0.0,0.0,2022-02-25,2022-02-21T17:44:57.970Z,0.0,NaN,NaN,NaN
25,NaN,False,2.0,46.0,NaN,BC25,mKI0NenT4UUfZ758N3WD,CONCLUÍDO,WEB FULL STACK,71.0,...,"[{'dataTermino': '2022-11-03', 'nome': 'ANGULA...",NaN,NaN,0.0,2023-01-16,NaN,0.0,"[FiqEWj5gfBZrOee7RXdUMgWBIxq1, jR4MN2vPlybXYgG...","[{'nome': 'José Almir de Souza Gomes Júnior', ...",mKI0NenT4UUfZ758N3WD
26,LUIZ PRANDINI,False,0.0,24.0,NaN,BC16,no9SFHd9Y39MDGFmZt8j,CONCLUÍDO,SALESFORCE,48.0,...,"[{'nome': 'HTML/CSS'}, {'nome': 'SALESFORCE DE...",4Mx2wYepkeSupFAaL0zUONlN0PG3,NaN,0.0,2022-06-28,NaN,0.0,"[4Mx2wYepkeSupFAaL0zUONlN0PG3, I0U8pfCzh7ctvk2...","[{'id': '4Mx2wYepkeSupFAaL0zUONlN0PG3', 'nome'...",NaN
27,IGOR GONDIM,False,0.0,35.0,NaN,BC12,o958myCwsjrQB8cxJc1K,CONCLUÍDO,ENGENHARIA DE DADOS,53.0,...,"[{'nome': 'PYTHON'}, {'nome': 'INFRA-CLOUD'}, ...",4nGZmWjPQ2TUoQfWWSi1bThad2O2,NaN,0.0,2022-04-15,NaN,1.0,NaN,NaN,NaN
28,NaN,True,NaN,NaN,NaN,AD1,uyMEdf66N9WqSJ35XSP1,EM ANDAMENTO,ANALISTA DE DADOS,NaN,...,"[{'dataTermino': '2023-02-26', 'dataInicio': '...",NaN,NaN,NaN,2023-05-18,NaN,NaN,"[4nGZmWjPQ2TUoQfWWSi1bThad2O2, 4w6ztCDqtZRT2gD...","[{'nome': 'Igor Gondim Soares de Lemos', 'id':...",uyMEdf66N9WqSJ35XSP1
29,NaN,True,NaN,NaN,NaN,RN1,wRUu8b24JA9teTnMPKto,EM ANDAMENTO,WEB FULL STACK,NaN,...,"[{'dataInicio': '2023-03-06', 'dataTermino': '...",NaN,NaN,NaN,2023-05-30,NaN,NaN,"[FiqEWj5gfBZrOee7RXdUMgWBIxq1, jR4MN2vPlybXYgG...","[{'id': 'FiqEWj5gfBZrOee7RXdUMgWBIxq1', 'nome'...",NaN
30,NaN,True,0.0,26.0,NaN,BC30,wobgaWWWgfZv2GNjVb6L,EM ANDAMENTO,MARTECH,50.0,...,"[{'dataInicio': '2022-12-13', 'nome': 'GESTÃO ...",NaN,NaN,0.0,2023-03-17,NaN,3.0,"[84CEVPFx9fgl2WuOjKd2wcgwKuJ3, i8vU3AsSqZRRam3...","[{'id': '84CEVPFx9fgl2WuOjKd2wcgwKuJ3', 'nome'...",wobgaWWWgfZv2GNjVb6L
31,NaN,True,0.0,0.0,NaN,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,56.0,...,"[{'nome': 'SALESFORCE DEV I', 'dataInicio': '2...",NaN,NaN,0.0,2023-05-18,NaN,0.0,"[I0U8pfCzh7ctvk2QdSRBIrmZhQS2, vFwIn8cbokc8eTp...","[{'nome': 'Lorena de Oliveira Meireles', 'id':...",xLRt9jNBT12FdUni1tXI
32,NaN,False,0.0,49.0,NaN,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,62.0,...,"[{'dataInicio': 'null', 'nome': 'SALESFORCE DE...",NaN,NaN,0.0,2023-01-20,NaN,1.0,"[uUS6yngVC0egyULQrKtY6lsksqf1, vFwIn8cbokc8eTp...","[{'id': 'uUS6yngVC0egyULQrKtY6lsksqf1', 'nome'...",yQbiG8kvfQxMUC7AXVAn

## Tratamento da coleção "Turmas"

### DISCIPLINAS

In [ ]:
df_disciplinas = df_turmas_bruto['disciplinas']

In [ ]:
logs = df_turmas_bruto.explode('disciplinas')
df_disciplinas = pd.json_normalize(json.loads(logs.to_json(orient="records")))

#lista de colunas para dropar
lista_colunas_drop_disciplinas = ['concluiram', 'dataDoBatch', 'estudantes', 'extensao', 'idProfessores',
                                  'key', 'porcentagemEmpregados', 'porcentagemIndicacao', 'processo',
                                  'professorUmId', 'professorUmNome', 'professorDoisId', 'professorDoisNome',
                                  'reciclagem', 'professores', 'naoEmpregaveis', 'formados', 'mediaTurma',
                                  'desistentes','recuperacao', 'empregados', 'disponiveis', 'cluster', 'ativo',
                                  'fimContrato', 'quantidadeAlunos', 'disciplinas.dataInicio', 'disciplinas.dataTermino']

df_disciplinas.drop(lista_colunas_drop_disciplinas,axis=1,inplace=True)
df_disciplinas

,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,dataInicio,dataTermino,disciplinas.nome
0,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,HTML/CSS
1,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,JAVASCRIPT
2,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,JQUERY/BOOTSTRAP
3,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,NODEJS
4,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,ANGULAR
...,...,...,...,...,...,...,...
146,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,2023-02-13,2023-05-18,SALESFORCE ADM
147,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE DEV I
148,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,PROJETO FINAL
149,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE DEV II
150,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE ADM

In [ ]:
df_disciplinas_bkp = df_disciplinas.copy()

In [ ]:
df_disciplinas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bootcampNome      151 non-null    object
 1   bootcampCodigo    151 non-null    object
 2   bootcampStatus    151 non-null    object
 3   bootcampTipo      151 non-null    object
 4   dataInicio        151 non-null    object
 5   dataTermino       151 non-null    object
 6   disciplinas.nome  151 non-null    object
dtypes: object(7)
memory usage: 8.4+ KB

#### Convertendo as datas de tipo objeto para data e trocando nomes de colunas para evitar erros no BigQuery

In [ ]:
df_disciplinas['dataInicio'] = pd.to_datetime(df_disciplinas['dataInicio'])
df_disciplinas['dataTermino'] = pd.to_datetime(df_disciplinas['dataTermino'])

In [ ]:
df_disciplinas

,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,dataInicio,dataTermino,disciplinas.nome
0,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,HTML/CSS
1,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,JAVASCRIPT
2,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,JQUERY/BOOTSTRAP
3,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,NODEJS
4,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,ANGULAR
...,...,...,...,...,...,...,...
146,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,2023-02-13,2023-05-18,SALESFORCE ADM
147,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE DEV I
148,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,PROJETO FINAL
149,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE DEV II
150,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE ADM

In [ ]:
df_disciplinas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bootcampNome      151 non-null    object
 1   bootcampCodigo    151 non-null    object
 2   bootcampStatus    151 non-null    object
 3   bootcampTipo      151 non-null    object
 4   dataInicio        151 non-null    datetime64[ns]
 5   dataTermino       151 non-null    datetime64[ns]
 6   disciplinas.nome  151 non-null    object
dtypes: datetime64[ns](2), object(5)
memory usage: 8.4+ KB

In [ ]:
df_disciplinas.rename(columns={'disciplinas.nome':'nome_disciplinas'},inplace=True)

In [ ]:
df_disciplinas

,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,dataInicio,dataTermino,nome_disciplinas
0,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,HTML/CSS
1,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,JAVASCRIPT
2,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,JQUERY/BOOTSTRAP
3,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,NODEJS
4,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,ANGULAR
...,...,...,...,...,...,...,...
146,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,2023-02-13,2023-05-18,SALESFORCE ADM
147,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE DEV I
148,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,PROJETO FINAL
149,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE DEV II
150,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,SALESFORCE ADM

#### Carregando DataFrame Disciplinas no Bucket do Projeto

In [ ]:
df_disciplinas.to_csv('gs://proj11/tratados/disciplinas.csv',index=False)

### PROFESSORES

In [ ]:
# função para criar o dicionário com os valores das outras colunas
def cria_lista(lin):
    lista_professores = []
    lista_professores.append({'nome': lin['professorUmNome'], 'id': lin['professorUmId']})
    lista_professores.append({'nome': lin['professorDoisNome'], 'id': lin['professorDoisId']})
    return lista_professores

In [ ]:
# aplicar a função cria_lista nas linhas com valores NaN na coluna "professores"
df_turmas_bruto.loc[df_turmas_bruto['professores'].isnull(), 'professores'] = (df_turmas_bruto
                                                                               [df_turmas_bruto['professores'].isnull()]
                                                                               .apply(cria_lista, axis=1))

df_professores_bruto = df_turmas_bruto.copy()

#### Normalizando o DF Professores

In [ ]:
# fazendo o explode da lista aninhada de professores
logs2 = df_professores_bruto.explode('professores', ignore_index=True)

# aplicando a função json_normalize para normalizar os dados e criar um novo dataframe de professores
df_professores = pd.json_normalize(json.loads(logs2.to_json(orient="records")))

# lista de colunas para dropar
lista_colunas_drop_professores = ['concluiram', 'dataDoBatch', 'estudantes', 'extensao', 'idProfessores', 'key',
                                  'porcentagemEmpregados', 'porcentagemIndicacao', 'processo', 'professorUmId',
                                  'professorUmNome', 'professorDoisId', 'professorDoisNome', 'reciclagem', 'disciplinas',
                                  'naoEmpregaveis', 'formados', 'mediaTurma', 'desistentes', 'recuperacao', 'empregados',
                                  'disponiveis', 'cluster', 'ativo', 'fimContrato', 'quantidadeAlunos']

# drop de colunas que não serão utilizadas
df_professores.drop(lista_colunas_drop_professores,axis=1,inplace=True)
df_professores

,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,dataInicio,dataTermino,professores.nome,professores.id
0,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,SAYURE VIEIRA DE PAIVA,l52ed8NxK0MQ9I8Tidiy3g0N0N12
1,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,FELIPE SOARES MUYLAERT BARROSO,aNEDifsCydcN7uFTZBo0q94DJ502
2,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,2021-08-30,2021-12-03,BISMARK WILLIAM GOMES DE ARAUJO,4w6ztCDqtZRT2gD35i59CupCyXr2
3,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,2021-08-30,2021-12-03,IGOR GONDIM SOARES DE LEMOS,4nGZmWjPQ2TUoQfWWSi1bThad2O2
4,BC13,6rHhoKZq8BFvYPbWGd0H,CONCLUÍDO,WEB FULL STACK,2021-01-31,2022-05-20,Tatiana Dias Chiacchio,djGodEEa8mZGArh4lm3gD30pCeg2
...,...,...,...,...,...,...,...,...
73,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,2023-02-13,2023-05-18,Renan Mussato,vFwIn8cbokc8eTpUt9QNbxP1hVe2
74,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,Filipe Santana de Oliveira,uUS6yngVC0egyULQrKtY6lsksqf1
75,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,Renan Mussato,vFwIn8cbokc8eTpUt9QNbxP1hVe2
76,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,Lorena de Oliveira Meireles,I0U8pfCzh7ctvk2QdSRBIrmZhQS2
77,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,Fernanda Soares,3QN1i1oocjh6YGA464z22iEY5rB2

In [ ]:
df_professores.rename(columns={'professores.nome':'nome_professores', 'professores.id': 'id_professores'},inplace=True)
df_professores["nome_professores"] = df_professores['nome_professores'].apply(lambda x: x.upper())

In [ ]:
df_professores

,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,dataInicio,dataTermino,nome_professores,id_professores
0,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,SAYURE VIEIRA DE PAIVA,l52ed8NxK0MQ9I8Tidiy3g0N0N12
1,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,FELIPE SOARES MUYLAERT BARROSO,aNEDifsCydcN7uFTZBo0q94DJ502
2,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,2021-08-30,2021-12-03,BISMARK WILLIAM GOMES DE ARAUJO,4w6ztCDqtZRT2gD35i59CupCyXr2
3,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,2021-08-30,2021-12-03,IGOR GONDIM SOARES DE LEMOS,4nGZmWjPQ2TUoQfWWSi1bThad2O2
4,BC13,6rHhoKZq8BFvYPbWGd0H,CONCLUÍDO,WEB FULL STACK,2021-01-31,2022-05-20,TATIANA DIAS CHIACCHIO,djGodEEa8mZGArh4lm3gD30pCeg2
...,...,...,...,...,...,...,...,...
73,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,2023-02-13,2023-05-18,RENAN MUSSATO,vFwIn8cbokc8eTpUt9QNbxP1hVe2
74,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,FILIPE SANTANA DE OLIVEIRA,uUS6yngVC0egyULQrKtY6lsksqf1
75,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,RENAN MUSSATO,vFwIn8cbokc8eTpUt9QNbxP1hVe2
76,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,LORENA DE OLIVEIRA MEIRELES,I0U8pfCzh7ctvk2QdSRBIrmZhQS2
77,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,FERNANDA SOARES,3QN1i1oocjh6YGA464z22iEY5rB2

#### Convertendo as datas de tipo objeto para data e trocando nomes de colunas para evitar erros no BigQuery

In [ ]:
df_professores['dataInicio'] = pd.to_datetime(df_professores['dataInicio'])
df_professores['dataTermino'] = pd.to_datetime(df_professores['dataTermino'])

In [ ]:
df_professores.rename(columns={'professores.nome':'nome_professores', 'professores.id': 'id_professores'},inplace=True)

In [ ]:
df_professores

,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,dataInicio,dataTermino,nome_professores,id_professores
0,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,SAYURE VIEIRA DE PAIVA,l52ed8NxK0MQ9I8Tidiy3g0N0N12
1,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,2021-07-19,2021-11-19,FELIPE SOARES MUYLAERT BARROSO,aNEDifsCydcN7uFTZBo0q94DJ502
2,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,2021-08-30,2021-12-03,BISMARK WILLIAM GOMES DE ARAUJO,4w6ztCDqtZRT2gD35i59CupCyXr2
3,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,2021-08-30,2021-12-03,IGOR GONDIM SOARES DE LEMOS,4nGZmWjPQ2TUoQfWWSi1bThad2O2
4,BC13,6rHhoKZq8BFvYPbWGd0H,CONCLUÍDO,WEB FULL STACK,2021-01-31,2022-05-20,TATIANA DIAS CHIACCHIO,djGodEEa8mZGArh4lm3gD30pCeg2
...,...,...,...,...,...,...,...,...
73,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,2023-02-13,2023-05-18,RENAN MUSSATO,vFwIn8cbokc8eTpUt9QNbxP1hVe2
74,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,FILIPE SANTANA DE OLIVEIRA,uUS6yngVC0egyULQrKtY6lsksqf1
75,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,RENAN MUSSATO,vFwIn8cbokc8eTpUt9QNbxP1hVe2
76,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,LORENA DE OLIVEIRA MEIRELES,I0U8pfCzh7ctvk2QdSRBIrmZhQS2
77,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,2022-10-17,2023-01-20,FERNANDA SOARES,3QN1i1oocjh6YGA464z22iEY5rB2

#### Carregando DataFrame Professores no Bucket do Projeto

In [ ]:
df_professores.to_csv('gs://proj11/tratados/professores.csv',index=False)

### TURMAS

In [ ]:
df_turmas = df_turmas_bruto.copy()

In [ ]:
# Preparação para exclusão
lista_colunas_drop_turmas = ['concluiram', 'dataDoBatch', 'disciplinas', 'estudantes', 'extensao',
                             'idProfessores', 'key', 'porcentagemEmpregados', 'porcentagemIndicacao',
                             'professorUmId', 'professorUmNome', 'professorDoisId', 'professorDoisNome', 
                             'processo', 'professores']
df_turmas.drop(lista_colunas_drop_turmas,axis=1,inplace=True)

In [ ]:
df_turmas = df_turmas.replace('<NA>', np.NaN)

In [ ]:
df_turmas['dataInicio'] = pd.to_datetime(df_turmas['dataInicio'])
df_turmas['dataTermino'] = pd.to_datetime(df_turmas['dataTermino'])

In [ ]:
df_turmas

,ativo,disponiveis,mediaTurma,bootcampNome,bootcampCodigo,bootcampStatus,bootcampTipo,quantidadeAlunos,recuperacao,dataInicio,fimContrato,desistentes,formados,naoEmpregaveis,empregados,reciclagem,dataTermino,cluster
0,False,6.0,8.0000,BC05,4HFs6bpe5QWfgBEtfpbT,CONCLUÍDO,WEB FULL STACK,55.0,0.0,2021-07-19,2022-02-17,5.0,49.0,10.0,39.0,27.0,2021-11-19,0.0
1,False,13.0,7.7000,BC06,6FFmCn0K9rpi4p7iLAMK,CONCLUÍDO,ENGENHARIA DE DADOS,53.0,0.0,2021-08-30,2022-03-03,6.0,45.0,9.0,31.0,15.0,2021-12-03,0.0
2,False,25.0,NaN,BC13,6rHhoKZq8BFvYPbWGd0H,CONCLUÍDO,WEB FULL STACK,52.0,0.0,2021-01-31,2021-08-29,11.0,37.0,14.0,11.0,0.0,2022-05-20,1.0
3,False,28.0,NaN,BC21,7uVovxasalK3skKfgvTA,CONCLUÍDO,SALESFORCE,58.0,0.0,2022-05-30,NaT,18.0,40.0,19.0,8.0,NaN,2022-08-23,2.0
4,False,6.0,8.0000,BC03,8zcCz89t7r2s0RcPdkIB,CONCLUÍDO,FRONT-END E MOBILE,40.0,0.0,2021-05-31,2021-12-30,4.0,33.0,8.0,26.0,1.0,2021-10-01,0.0
5,False,11.0,NaN,BC15,CEKdYcPHEBjSIvAMxO1F,CONCLUÍDO,SALESFORCE,28.0,0.0,2022-03-07,2022-08-29,2.0,24.0,4.0,12.0,NaN,2022-05-31,1.0
6,False,27.0,NaN,BC22,CUZKZA6JtB8SUoPsCRVW,CONCLUÍDO,WEB FULL STACK,55.0,1.0,2022-06-06,NaT,16.0,31.0,24.0,2.0,NaN,2022-09-28,0.0
7,False,42.0,NaN,BC26,GDEAJXvFmdhHgnlrVsCt,CONCLUÍDO,ENGENHARIA DE DADOS,68.0,0.0,2022-10-17,NaT,9.0,59.0,9.0,0.0,NaN,2023-01-20,14.0
8,False,0.0,8.6000,BC02,Ic5EWwr6MEMoGvSdkrR7,CONCLUÍDO,WEB FULL STACK,28.0,0.0,2021-03-03,2021-10-07,1.0,27.0,1.0,27.0,1.0,2021-07-09,0.0
9,False,13.0,NaN,BC19,JVH8fHm97DwTI07N1YNM,CONCLUÍDO,MARTECH,42.0,0.0,2022-05-23,NaT,17.0,20.0,21.0,6.0,NaN,2022-08-16,2.0
10,False,33.0,NaN,BC23,JxMZHyh2I3RR2loFaG1p,CONCLUÍDO,ENGENHARIA DE DADOS,55.0,0.0,2022-06-27,NaT,12.0,43.0,14.0,7.0,NaN,2022-09-19,0.0
11,False,20.0,7.6875,BC07,Nl0qBrwZ4IoSc5OwpefU,CONCLUÍDO,WEB FULL STACK,45.0,0.0,2021-09-20,2022-04-28,6.0,39.0,6.0,19.0,34.0,2022-01-28,0.0
12,False,36.0,NaN,BC24,OvL1dam3Yy4IzlgP4TJm,CONCLUÍDO,SALESFORCE,52.0,0.0,2022-07-11,NaT,8.0,44.0,8.0,6.0,NaN,2022-10-03,0.0
13,False,20.0,NaN,BC17,UDHyPuSEWNLMvENjOro6,CONCLUÍDO,ENGENHARIA DE DADOS,54.0,0.0,2022-03-28,2022-09-19,20.0,31.0,22.0,11.0,NaN,2022-06-21,1.0
14,False,5.0,NaN,BC11,XeNHNAaEGqIkWSEsAjLP,CONCLUÍDO,SALESFORCE,47.0,0.0,2021-12-01,2022-05-26,13.0,33.0,16.0,26.0,0.0,2022-02-25,0.0
15,False,15.0,NaN,BC14,YhaiPrTxiFLS65fDfsJj,CONCLUÍDO,MARTECH,39.0,0.0,2022-01-31,2022-07-28,12.0,27.0,13.0,10.0,0.0,2022-04-29,0.0
16,False,15.0,7.8000,BC09,ZMvcHSfZH1t1WZLDx8Vs,CONCLUÍDO,WEB FULL STACK,50.0,0.0,2021-11-16,2022-06-16,9.0,39.0,11.0,23.0,0.0,2022-03-18,0.0
17,False,26.0,NaN,BC20,eMz0vb5K5dngm2wUoUIr,CONCLUÍDO,WEB FULL STACK,51.0,0.0,2022-05-09,NaT,10.0,34.0,18.0,5.0,NaN,2022-08-30,0.0
18,False,39.0,NaN,BC29,eUiJfVtDc9A1YKftT38z,CONCLUÍDO,MARTECH,63.0,0.0,2022-08-29,NaT,20.0,37.0,24.0,0.0,NaN,2022-11-25,0.0
19,False,23.0,NaN,BC18,gEqsxZBau69FlCUCIQ6W,CONCLUÍDO,WEB FULL STACK,57.0,0.0,2022-04-04,NaT,16.0,33.0,21.0,11.0,NaN,2022-07-29,0.0
20,False,1.0,8.3000,BC01,hx5dHDdRlX6q1LAysknt,CONCLUÍDO,WEB FULL STACK,30.0,0.0,2021-02-03,2021-08-29,5.0,25.0,5.0,24.0,2.0,2021-05-31,0.0
21,False,2.0,6.6000,BC04,hzymD9j5KwP9r4Ae33t3,CONCLUÍDO,GOOGLE CLOUD COMPUTING,40.0,0.0,2021-06-14,2021-11-10,6.0,27.0,13.0,25.0,0.0,2021-08-12,0.0
22,False,25.0,NaN,BC27,jHXYKk7zodgzbHQX0bZv,CONCLUÍDO,SERVICENOW,43.0,0.0,2022-11-16,NaT,13.0,29.0,14.0,0.0,NaN,2023-02-17,4.0
23,False,14.0,7.9000,BC08,koH17PebhftgjcWzxQFc,CONCLUÍDO,ENGENHARIA DE DADOS,52.0,0.0,2021-10-25,2022-04-28,8.0,42.0,10.0,28.0,0.0,2022-01-28,0.0
24,False,8.0,NaN,BC10,lCWu2zPwrWCyIijGjS4c,CONCLUÍDO,SALESFORCE,57.0,0.0,2021-12-01,2022-05-26,14.0,43.0,15.0,34.0,0.0,2022-02-25,0.0
25,False,46.0,NaN,BC25,mKI0NenT4UUfZ758N3WD,CONCLUÍDO,WEB FULL STACK,71.0,13.0,2022-09-14,NaT,6.0,50.0,8.0,2.0,NaN,2023-01-16,0.0
26,False,24.0,NaN,BC16,no9SFHd9Y39MDGFmZt8j,CONCLUÍDO,SALESFORCE,48.0,0.0,2022-04-04,NaT,15.0,31.0,16.0,8.0,NaN,2022-06-28,0.0
27,False,35.0,NaN,BC12,o958myCwsjrQB8cxJc1K,CONCLUÍDO,ENGENHARIA DE DADOS,53.0,0.0,2022-01-17,2022-07-14,9.0,43.0,11.0,6.0,NaN,2022-04-15,1.0
28,True,NaN,NaN,AD1,uyMEdf66N9WqSJ35XSP1,EM ANDAMENTO,ANALISTA DE DADOS,NaN,NaN,2023-02-13,NaT,NaN,NaN,NaN,NaN,NaN,2023-05-18,NaN
29,True,NaN,NaN,RN1,wRUu8b24JA9teTnMPKto,EM ANDAMENTO,WEB FULL STACK,NaN,NaN,2023-02-13,NaT,NaN,NaN,NaN,NaN,NaN,2023-05-30,NaN
30,True,26.0,NaN,BC30,wobgaWWWgfZv2GNjVb6L,EM ANDAMENTO,MARTECH,50.0,6.0,2022-12-05,NaT,15.0,29.0,15.0,0.0,NaN,2023-03-17,3.0
31,True,0.0,NaN,SF8,xLRt9jNBT12FdUni1tXI,EM ANDAMENTO,SALESFORCE,56.0,0.0,2023-02-13,NaT,5.0,0.0,5.0,0.0,NaN,2023-05-18,0.0
32,False,49.0,NaN,BC28,yQbiG8kvfQxMUC7AXVAn,CONCLUÍDO,SALESFORCE,62.0,0.0,2022-10-17,NaT,12.0,50.0,12.0,0.0,NaN,2023-01-20,1.0

In [ ]:
df_turmas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ativo             33 non-null     bool
 1   disponiveis       31 non-null     float64
 2   mediaTurma        9 non-null      float64
 3   bootcampNome      33 non-null     object
 4   bootcampCodigo    33 non-null     object
 5   bootcampStatus    33 non-null     object
 6   bootcampTipo      33 non-null     object
 7   quantidadeAlunos  31 non-null     float64
 8   recuperacao       31 non-null     float64
 9   dataInicio        33 non-null     datetime64[ns]
 10  fimContrato       16 non-null     datetime64[ns]
 11  desistentes       31 non-null     float64
 12  formados          31 non-null     float64
 13  naoEmpregaveis    31 non-null     float64
 14  empregados        31 non-null     float64
 15  reciclagem        13 non-null     float64
 16  dataTermino       33 non-null     datetime64[ns]
 17  cluster           31 non-null     float64
dtypes: bool(1), datetime64[ns](3), float64(10), object(4)
memory usage: 4.5+ KB

#### Carregando DataFrame Turmas no Bucket do Projeto

In [ ]:
df_turmas.to_csv('gs://proj11/tratados/turmas.csv',index=False)

##Transformações no dataframe de estudantes

O proximo trecho de codigo realiza o seguinte:

1.Acessa a coleção "Estudantes" em um banco de dados Firestore, que é um banco de dados NoSQL oferecido pela plataforma Google Cloud.

2.Recupera os documentos (ou registros) da coleção "Estudantes" usando o método get() da referência da coleção "estudantes_ref". Esses documentos são retornados como um objeto QuerySnapshot.

3.Cria uma lista "data" que contém um dicionário para cada documento da coleção "Estudantes", com exceção da chave "notas". O dicionário é criado usando o método to_dict() do objeto DocumentSnapshot, que converte o documento para um dicionário Python.

4.Normaliza os dados em formato JSON dentro da lista "data" e cria um DataFrame Pandas chamado "df_normalize". Isso é feito usando o método pd.json_normalize(), que converte o formato JSON em um DataFrame Pandas.

Portanto, o objetivo final é criar um DataFrame Pandas que contenha os dados da coleção "Estudantes", exceto a coluna "notas". A coluna "notas" é removida da lista de dicionários antes de converter os dados para JSON para garantir que não apareça no DataFrame resultante.

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [ ]:
#Apenas as colunas que não são a "colunas_drop" serão incluídas no dataframe resultante
colunas_drop = ['bairro', 'CEP', 'cep', 'complemento', 'cpf',
                'dataDoBatch', 'email', 'experienciaProfissional', 'foto',
                'graduation', 'historico', 'idiomas', 'inglesInicial',
                'nivelIngles', 'nacionalidade', 'notas', 'numero', 'objetivos',
                'observacoes', 'rua', 'telefone']

#O dicionário é criado usando o método to_dict() que converte o documento para um dicionário Python
data = [{k:v for k,v in doc.to_dict().items() if k not in colunas_drop} for doc in estudantes_docs]

#Normaliza os dados em formato JSON dentro da lista "data" e cria um DataFrame Pandas chamado "df_normalize
df_normalize = pd.json_normalize(data)

In [ ]:
df_normalize

,bootcampTipo,tipoDeficiencia,genero,statusEmpregabilidade,disponibilidadeMudanca,uf,mediaFinal,etnia,filhos,areaFormacao,statusNoBootcamp,parceiroAssociado,bootcampCodigo,id,favorito,dataNascimento,formacaoAcademica,nomeCompleto,estadoCivil,cidade,escolaridadeNivel,deficiencia,nomeSocial,bootcampNome,empregabilidadeLastUpdate,empregabilidadeUpdateBy.uid,empregabilidadeUpdateBy.type,nomeDoCursoSuperior
0,Google Cloud Computing,,Feminino,Empregado,,PR,7,Branco,Não informado,Ciências Humanas e Sociais,Formado,GLOBAL HITSS,hzymD9j5KwP9r4Ae33t3,01q3O0Z8RJyT0q7bdHZp,False,698700449074,[],FRANCELLOISE ANTUNES CARDOSO,Não informado,Curitiba,Educação Superior Completo,,FRANCELLOISE,BC04,NaN,NaN,NaN,NaN
1,Engenharia de Dados,,Masculino,Empregado,,PE,5.73,Pardo,0,Ciências Exatas,Formado,[EXTERNO],6FFmCn0K9rpi4p7iLAMK,04oog90rzyRPyQdruFQQ,False,667164449077,[],WALLACE ALMEIDA VALERIANO,Solteiro,Custódia,Educação Superior Incompleto,,WALLACE,BC06,NaN,NaN,NaN,NaN
2,Salesforce,,Feminino,Não Empregável,,SP,NaN,Pardo,NaN,NaN,Desistente,,OvL1dam3Yy4IzlgP4TJm,08DFPlaZHy7EKM2iigsa,False,499737600000,Ciência da Computação,MAGDA DANTAS SANTANA,Casada,SÃO PAULO,Educação Superior Completo,Não,,BC24,NaN,NaN,NaN,NaN
3,Salesforce,,Masculino,Não Empregável,,SP,NaN,Branco,NaN,NaN,Desistente,,OvL1dam3Yy4IzlgP4TJm,0BMulajtduVo1wT7yDsO,False,782438400000,Análise e Desenvolvimento de Sistemas,DENER AUGUSTO DOS ANJOS OLIVEIRA,Solteiro,SUMARÉ,Educação Superior Incompleto,Não,,BC24,NaN,NaN,NaN,NaN
4,Salesforce,,Masculino,Não Empregável,,SP,NaN,Branco,NaN,NaN,Desistente,,OvL1dam3Yy4IzlgP4TJm,0G9LjTAzN9GRdyBXUcxW,False,579225600000,,THOMAZ NOBUKI PEREIRA,Divorciado,OSASCO,NaN,Não,,BC24,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Salesforce,,Masculino,Empregado,,PE,7.6,Pardo,Não informado,Ciências Exatas,Formado,[DELOITTE],lCWu2zPwrWCyIijGjS4c,zty1iQUdFZy0fIkk8cqZ,False,256931097982,[],FÁBIO FERREIRA DOS SANTOS,Não informado,Jaboatão dos Guararapes,Educação Superior Completo,,FÁBIO,BC10,NaN,NaN,NaN,NaN
1684,Analista de Dados,,Masculino,Em Formação,,RJ,NaN,Branco,NaN,NaN,Cursando,,uyMEdf66N9WqSJ35XSP1,zv0TpnVdxDTObTc2Q8hw,False,696902400000,NaN,RAPHAEL PACHECO XAVIER,,RIO DE JANEIRO,Ensino Médio,,,AD1,NaN,NaN,NaN,NaN
1685,Web Full Stack,,Feminino,Empregado,,RS,9.6,Branco,0,Não informado,Formado,GLOBAL HITSS,hx5dHDdRlX6q1LAysknt,zw56ykXNM5TEH54tSGG9,False,635628449069,[],ALINE PACHECO MARTINS,Casado,Porto Alegre,Não informado,,ALINE,BC01,NaN,NaN,NaN,NaN
1686,Engenharia de Dados,,Masculino,Empregado,,RJ,8.6,Branco,Não informado,Ciências Exatas,Formado,[EXTERNO],koH17PebhftgjcWzxQFc,zwWs8hZhd6zPGSflTm9S,False,761858849079,[],HUGO PEDRA GONÇALVES,Não informado,Rio de Janeiro,Mestrado,,HUGO,BC08,Wed Jun 08 2022 15:36:15 GMT+0000 (Coordinated...,VpXRjNf22MNy6oSLvh9jxF60dpC2,Placement,NaN
1687,Analista de Dados,,Masculino,Em Formação,,MG,NaN,Pardo,NaN,NaN,Cursando,,uyMEdf66N9WqSJ35XSP1,zy2F1KMsPkWLqNvUWvk6,False,978307200000,NaN,VICTOR HUGO PAULA RODRIGUES,,Uberlândia,Mestrado,,,AD1,NaN,NaN,NaN,NaN

In [ ]:
df_normalize.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1688 entries, 0 to 1687
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   bootcampTipo                  1688 non-null   object
 1   tipoDeficiencia               1688 non-null   object
 2   genero                        1688 non-null   object
 3   statusEmpregabilidade         1688 non-null   object
 4   disponibilidadeMudanca        1688 non-null   object
 5   uf                            1688 non-null   object
 6   mediaFinal                    588 non-null    object
 7   etnia                         1688 non-null   object
 8   filhos                        588 non-null    object
 9   areaFormacao                  1199 non-null   object
 10  statusNoBootcamp              1688 non-null   object
 11  parceiroAssociado             1688 non-null   object
 12  bootcampCodigo                1688 non-null   object
 13  id                            1688 non-null   object
 14  favorito                      1688 non-null   object
 15  dataNascimento                1688 non-null   object
 16  formacaoAcademica             1401 non-null   object
 17  nomeCompleto                  1688 non-null   object
 18  estadoCivil                   1688 non-null   object
 19  cidade                        1688 non-null   object
 20  escolaridadeNivel             1646 non-null   object
 21  deficiencia                   1688 non-null   object
 22  nomeSocial                    1688 non-null   object
 23  bootcampNome                  1688 non-null   object
 24  empregabilidadeLastUpdate     392 non-null    object
 25  empregabilidadeUpdateBy.uid   392 non-null    object
 26  empregabilidadeUpdateBy.type  392 non-null    object
 27  nomeDoCursoSuperior           184 non-null    object
dtypes: object(28)
memory usage: 369.4+ KB

###Criação do df novo com coluna agrupadas

In [ ]:
# Criando grupos de colunas relacionadas
grupo1 = ['nomeCompleto', 'id', 'dataNascimento', 'genero', 'etnia', 'estadoCivil', 'cidade', 'uf']
grupo2 = ['deficiencia', 'tipoDeficiencia']
grupo3 = ['disponibilidadeMudanca']
grupo4 = ['escolaridadeNivel', 'formacaoAcademica', 'nomeDoCursoSuperior', 'areaFormacao']
grupo5 = ['bootcampNome', 'bootcampTipo', 'bootcampCodigo', 'parceiroAssociado', 'statusNoBootcamp']
grupo6 = ['statusEmpregabilidade', 'empregabilidadeLastUpdate', 'empregabilidadeUpdateBy.type', 'empregabilidadeUpdateBy.uid']
grupo7 = ['favorito']
grupo8 = ['filhos']
grupo9 = ['mediaFinal']

In [ ]:
# Reordenando o dataframe com as colunas em grupos relacionados
df = df_normalize[grupo1 + grupo2 + grupo3 + grupo4 + grupo5 + grupo6 + grupo7 + grupo8 + grupo9]

In [ ]:
df

,nomeCompleto,id,dataNascimento,genero,etnia,estadoCivil,cidade,uf,deficiencia,tipoDeficiencia,disponibilidadeMudanca,escolaridadeNivel,formacaoAcademica,nomeDoCursoSuperior,areaFormacao,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate,empregabilidadeUpdateBy.type,empregabilidadeUpdateBy.uid,favorito,filhos,mediaFinal
0,FRANCELLOISE ANTUNES CARDOSO,01q3O0Z8RJyT0q7bdHZp,698700449074,Feminino,Branco,Não informado,Curitiba,PR,,,,Educação Superior Completo,[],NaN,Ciências Humanas e Sociais,BC04,Google Cloud Computing,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,Não informado,7
1,WALLACE ALMEIDA VALERIANO,04oog90rzyRPyQdruFQQ,667164449077,Masculino,Pardo,Solteiro,Custódia,PE,,,,Educação Superior Incompleto,[],NaN,Ciências Exatas,BC06,Engenharia de Dados,6FFmCn0K9rpi4p7iLAMK,[EXTERNO],Formado,Empregado,NaN,NaN,NaN,False,0,5.73
2,MAGDA DANTAS SANTANA,08DFPlaZHy7EKM2iigsa,499737600000,Feminino,Pardo,Casada,SÃO PAULO,SP,Não,,,Educação Superior Completo,Ciência da Computação,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN
3,DENER AUGUSTO DOS ANJOS OLIVEIRA,0BMulajtduVo1wT7yDsO,782438400000,Masculino,Branco,Solteiro,SUMARÉ,SP,Não,,,Educação Superior Incompleto,Análise e Desenvolvimento de Sistemas,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN
4,THOMAZ NOBUKI PEREIRA,0G9LjTAzN9GRdyBXUcxW,579225600000,Masculino,Branco,Divorciado,OSASCO,SP,Não,,,NaN,,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,FÁBIO FERREIRA DOS SANTOS,zty1iQUdFZy0fIkk8cqZ,256931097982,Masculino,Pardo,Não informado,Jaboatão dos Guararapes,PE,,,,Educação Superior Completo,[],NaN,Ciências Exatas,BC10,Salesforce,lCWu2zPwrWCyIijGjS4c,[DELOITTE],Formado,Empregado,NaN,NaN,NaN,False,Não informado,7.6
1684,RAPHAEL PACHECO XAVIER,zv0TpnVdxDTObTc2Q8hw,696902400000,Masculino,Branco,,RIO DE JANEIRO,RJ,,,,Ensino Médio,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN
1685,ALINE PACHECO MARTINS,zw56ykXNM5TEH54tSGG9,635628449069,Feminino,Branco,Casado,Porto Alegre,RS,,,,Não informado,[],NaN,Não informado,BC01,Web Full Stack,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,0,9.6
1686,HUGO PEDRA GONÇALVES,zwWs8hZhd6zPGSflTm9S,761858849079,Masculino,Branco,Não informado,Rio de Janeiro,RJ,,,,Mestrado,[],NaN,Ciências Exatas,BC08,Engenharia de Dados,koH17PebhftgjcWzxQFc,[EXTERNO],Formado,Empregado,Wed Jun 08 2022 15:36:15 GMT+0000 (Coordinated...,Placement,VpXRjNf22MNy6oSLvh9jxF60dpC2,False,Não informado,8.6
1687,VICTOR HUGO PAULA RODRIGUES,zy2F1KMsPkWLqNvUWvk6,978307200000,Masculino,Pardo,,Uberlândia,MG,,,,Mestrado,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN

In [ ]:
df.shape

(1688, 27)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1688 entries, 0 to 1687
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   nomeCompleto                  1688 non-null   object
 1   id                            1688 non-null   object
 2   dataNascimento                1688 non-null   object
 3   genero                        1688 non-null   object
 4   etnia                         1688 non-null   object
 5   estadoCivil                   1688 non-null   object
 6   cidade                        1688 non-null   object
 7   uf                            1688 non-null   object
 8   deficiencia                   1688 non-null   object
 9   tipoDeficiencia               1688 non-null   object
 10  disponibilidadeMudanca        1688 non-null   object
 11  escolaridadeNivel             1646 non-null   object
 12  formacaoAcademica             1401 non-null   object
 13  nomeDoCursoSuperior           184 non-null    object
 14  areaFormacao                  1199 non-null   object
 15  bootcampNome                  1688 non-null   object
 16  bootcampTipo                  1688 non-null   object
 17  bootcampCodigo                1688 non-null   object
 18  parceiroAssociado             1688 non-null   object
 19  statusNoBootcamp              1688 non-null   object
 20  statusEmpregabilidade         1688 non-null   object
 21  empregabilidadeLastUpdate     392 non-null    object
 22  empregabilidadeUpdateBy.type  392 non-null    object
 23  empregabilidadeUpdateBy.uid   392 non-null    object
 24  favorito                      1688 non-null   object
 25  filhos                        588 non-null    object
 26  mediaFinal                    588 non-null    object
dtypes: object(27)
memory usage: 356.2+ KB

###Formatar a data de nascimento

In [ ]:
# removendo os textos e valores "0"
df['dataNascimentoTratada'] = df['dataNascimento'].replace(['nao informado','Não informado', 0, ''], np.nan)

# removendo o sinal negativo
df['dataNascimentoTratada'] = abs(df['dataNascimentoTratada'])

# convertendo a data em milisegundos para data
df['dataNascimentoTratada'] = pd.to_datetime(df['dataNascimentoTratada'], unit='ms').dt.date

# convertendo a nova coluda para tipo data
df['dataNascimentoTratada'] = pd.to_datetime(df['dataNascimentoTratada'])

In [ ]:
df

,nomeCompleto,id,dataNascimento,genero,etnia,estadoCivil,cidade,uf,deficiencia,tipoDeficiencia,disponibilidadeMudanca,escolaridadeNivel,formacaoAcademica,nomeDoCursoSuperior,areaFormacao,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate,empregabilidadeUpdateBy.type,empregabilidadeUpdateBy.uid,favorito,filhos,mediaFinal,dataNascimentoTratada
0,FRANCELLOISE ANTUNES CARDOSO,01q3O0Z8RJyT0q7bdHZp,698700449074,Feminino,Branco,Não informado,Curitiba,PR,,,,Educação Superior Completo,[],NaN,Ciências Humanas e Sociais,BC04,Google Cloud Computing,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,Não informado,7,1992-02-21
1,WALLACE ALMEIDA VALERIANO,04oog90rzyRPyQdruFQQ,667164449077,Masculino,Pardo,Solteiro,Custódia,PE,,,,Educação Superior Incompleto,[],NaN,Ciências Exatas,BC06,Engenharia de Dados,6FFmCn0K9rpi4p7iLAMK,[EXTERNO],Formado,Empregado,NaN,NaN,NaN,False,0,5.73,1991-02-21
2,MAGDA DANTAS SANTANA,08DFPlaZHy7EKM2iigsa,499737600000,Feminino,Pardo,Casada,SÃO PAULO,SP,Não,,,Educação Superior Completo,Ciência da Computação,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1985-11-02
3,DENER AUGUSTO DOS ANJOS OLIVEIRA,0BMulajtduVo1wT7yDsO,782438400000,Masculino,Branco,Solteiro,SUMARÉ,SP,Não,,,Educação Superior Incompleto,Análise e Desenvolvimento de Sistemas,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1994-10-18
4,THOMAZ NOBUKI PEREIRA,0G9LjTAzN9GRdyBXUcxW,579225600000,Masculino,Branco,Divorciado,OSASCO,SP,Não,,,NaN,,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1988-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,FÁBIO FERREIRA DOS SANTOS,zty1iQUdFZy0fIkk8cqZ,256931097982,Masculino,Pardo,Não informado,Jaboatão dos Guararapes,PE,,,,Educação Superior Completo,[],NaN,Ciências Exatas,BC10,Salesforce,lCWu2zPwrWCyIijGjS4c,[DELOITTE],Formado,Empregado,NaN,NaN,NaN,False,Não informado,7.6,1978-02-21
1684,RAPHAEL PACHECO XAVIER,zv0TpnVdxDTObTc2Q8hw,696902400000,Masculino,Branco,,RIO DE JANEIRO,RJ,,,,Ensino Médio,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN,1992-02-01
1685,ALINE PACHECO MARTINS,zw56ykXNM5TEH54tSGG9,635628449069,Feminino,Branco,Casado,Porto Alegre,RS,,,,Não informado,[],NaN,Não informado,BC01,Web Full Stack,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,0,9.6,1990-02-21
1686,HUGO PEDRA GONÇALVES,zwWs8hZhd6zPGSflTm9S,761858849079,Masculino,Branco,Não informado,Rio de Janeiro,RJ,,,,Mestrado,[],NaN,Ciências Exatas,BC08,Engenharia de Dados,koH17PebhftgjcWzxQFc,[EXTERNO],Formado,Empregado,Wed Jun 08 2022 15:36:15 GMT+0000 (Coordinated...,Placement,VpXRjNf22MNy6oSLvh9jxF60dpC2,False,Não informado,8.6,1994-02-21
1687,VICTOR HUGO PAULA RODRIGUES,zy2F1KMsPkWLqNvUWvk6,978307200000,Masculino,Pardo,,Uberlândia,MG,,,,Mestrado,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN,2001-01-01

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1688 entries, 0 to 1687
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   nomeCompleto                  1688 non-null   object
 1   id                            1688 non-null   object
 2   dataNascimento                1688 non-null   object
 3   genero                        1688 non-null   object
 4   etnia                         1688 non-null   object
 5   estadoCivil                   1688 non-null   object
 6   cidade                        1688 non-null   object
 7   uf                            1688 non-null   object
 8   deficiencia                   1688 non-null   object
 9   tipoDeficiencia               1688 non-null   object
 10  disponibilidadeMudanca        1688 non-null   object
 11  escolaridadeNivel             1646 non-null   object
 12  formacaoAcademica             1401 non-null   object
 13  nomeDoCursoSuperior           184 non-null    object
 14  areaFormacao                  1199 non-null   object
 15  bootcampNome                  1688 non-null   object
 16  bootcampTipo                  1688 non-null   object
 17  bootcampCodigo                1688 non-null   object
 18  parceiroAssociado             1688 non-null   object
 19  statusNoBootcamp              1688 non-null   object
 20  statusEmpregabilidade         1688 non-null   object
 21  empregabilidadeLastUpdate     392 non-null    object
 22  empregabilidadeUpdateBy.type  392 non-null    object
 23  empregabilidadeUpdateBy.uid   392 non-null    object
 24  favorito                      1688 non-null   object
 25  filhos                        588 non-null    object
 26  mediaFinal                    588 non-null    object
 27  dataNascimentoTratada         1468 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(27)
memory usage: 369.4+ KB

###Padronização de texto das colunas

#### Tratamento listas vazias e valores ausentes

In [ ]:
#backup
df_backup = df.copy()

In [ ]:
#Reescreve com o backup o df original
df = df_backup.copy()

In [ ]:
df

,nomeCompleto,id,dataNascimento,genero,etnia,estadoCivil,cidade,uf,deficiencia,tipoDeficiencia,disponibilidadeMudanca,escolaridadeNivel,formacaoAcademica,nomeDoCursoSuperior,areaFormacao,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate,empregabilidadeUpdateBy.type,empregabilidadeUpdateBy.uid,favorito,filhos,mediaFinal,dataNascimentoTratada
0,FRANCELLOISE ANTUNES CARDOSO,01q3O0Z8RJyT0q7bdHZp,698700449074,Feminino,Branco,Não informado,Curitiba,PR,,,,Educação Superior Completo,[],NaN,Ciências Humanas e Sociais,BC04,Google Cloud Computing,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,Não informado,7,1992-02-21
1,WALLACE ALMEIDA VALERIANO,04oog90rzyRPyQdruFQQ,667164449077,Masculino,Pardo,Solteiro,Custódia,PE,,,,Educação Superior Incompleto,[],NaN,Ciências Exatas,BC06,Engenharia de Dados,6FFmCn0K9rpi4p7iLAMK,[EXTERNO],Formado,Empregado,NaN,NaN,NaN,False,0,5.73,1991-02-21
2,MAGDA DANTAS SANTANA,08DFPlaZHy7EKM2iigsa,499737600000,Feminino,Pardo,Casada,SÃO PAULO,SP,Não,,,Educação Superior Completo,Ciência da Computação,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1985-11-02
3,DENER AUGUSTO DOS ANJOS OLIVEIRA,0BMulajtduVo1wT7yDsO,782438400000,Masculino,Branco,Solteiro,SUMARÉ,SP,Não,,,Educação Superior Incompleto,Análise e Desenvolvimento de Sistemas,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1994-10-18
4,THOMAZ NOBUKI PEREIRA,0G9LjTAzN9GRdyBXUcxW,579225600000,Masculino,Branco,Divorciado,OSASCO,SP,Não,,,NaN,,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1988-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,FÁBIO FERREIRA DOS SANTOS,zty1iQUdFZy0fIkk8cqZ,256931097982,Masculino,Pardo,Não informado,Jaboatão dos Guararapes,PE,,,,Educação Superior Completo,[],NaN,Ciências Exatas,BC10,Salesforce,lCWu2zPwrWCyIijGjS4c,[DELOITTE],Formado,Empregado,NaN,NaN,NaN,False,Não informado,7.6,1978-02-21
1684,RAPHAEL PACHECO XAVIER,zv0TpnVdxDTObTc2Q8hw,696902400000,Masculino,Branco,,RIO DE JANEIRO,RJ,,,,Ensino Médio,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN,1992-02-01
1685,ALINE PACHECO MARTINS,zw56ykXNM5TEH54tSGG9,635628449069,Feminino,Branco,Casado,Porto Alegre,RS,,,,Não informado,[],NaN,Não informado,BC01,Web Full Stack,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,0,9.6,1990-02-21
1686,HUGO PEDRA GONÇALVES,zwWs8hZhd6zPGSflTm9S,761858849079,Masculino,Branco,Não informado,Rio de Janeiro,RJ,,,,Mestrado,[],NaN,Ciências Exatas,BC08,Engenharia de Dados,koH17PebhftgjcWzxQFc,[EXTERNO],Formado,Empregado,Wed Jun 08 2022 15:36:15 GMT+0000 (Coordinated...,Placement,VpXRjNf22MNy6oSLvh9jxF60dpC2,False,Não informado,8.6,1994-02-21
1687,VICTOR HUGO PAULA RODRIGUES,zy2F1KMsPkWLqNvUWvk6,978307200000,Masculino,Pardo,,Uberlândia,MG,,,,Mestrado,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN,2001-01-01

In [ ]:
#Função que puxa elementos das listas
def remove_lists(x):
    if isinstance(x, list):
        if len(x) > 0:
            return x[0]
        else:
            return np.NaN
    else:
        return x

#Função applymap para executar em cada elemento individualmente
df = df.applymap(remove_lists)

#Substituir diferentes variações de valores ausentes
df.replace(['', pd.NA, 'NaN', 'nan'], np.NaN, inplace=True)

In [ ]:
df

,nomeCompleto,id,dataNascimento,genero,etnia,estadoCivil,cidade,uf,deficiencia,tipoDeficiencia,disponibilidadeMudanca,escolaridadeNivel,formacaoAcademica,nomeDoCursoSuperior,areaFormacao,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate,empregabilidadeUpdateBy.type,empregabilidadeUpdateBy.uid,favorito,filhos,mediaFinal,dataNascimentoTratada
0,FRANCELLOISE ANTUNES CARDOSO,01q3O0Z8RJyT0q7bdHZp,698700449074,Feminino,Branco,Não informado,Curitiba,PR,NaN,NaN,NaN,Educação Superior Completo,NaN,NaN,Ciências Humanas e Sociais,BC04,Google Cloud Computing,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,Não informado,7,1992-02-21
1,WALLACE ALMEIDA VALERIANO,04oog90rzyRPyQdruFQQ,667164449077,Masculino,Pardo,Solteiro,Custódia,PE,NaN,NaN,NaN,Educação Superior Incompleto,NaN,NaN,Ciências Exatas,BC06,Engenharia de Dados,6FFmCn0K9rpi4p7iLAMK,EXTERNO,Formado,Empregado,NaN,NaN,NaN,False,0,5.73,1991-02-21
2,MAGDA DANTAS SANTANA,08DFPlaZHy7EKM2iigsa,499737600000,Feminino,Pardo,Casada,SÃO PAULO,SP,Não,NaN,NaN,Educação Superior Completo,Ciência da Computação,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,NaN,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1985-11-02
3,DENER AUGUSTO DOS ANJOS OLIVEIRA,0BMulajtduVo1wT7yDsO,782438400000,Masculino,Branco,Solteiro,SUMARÉ,SP,Não,NaN,NaN,Educação Superior Incompleto,Análise e Desenvolvimento de Sistemas,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,NaN,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1994-10-18
4,THOMAZ NOBUKI PEREIRA,0G9LjTAzN9GRdyBXUcxW,579225600000,Masculino,Branco,Divorciado,OSASCO,SP,Não,NaN,NaN,NaN,NaN,NaN,NaN,BC24,Salesforce,OvL1dam3Yy4IzlgP4TJm,NaN,Desistente,Não Empregável,NaN,NaN,NaN,False,NaN,NaN,1988-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,FÁBIO FERREIRA DOS SANTOS,zty1iQUdFZy0fIkk8cqZ,256931097982,Masculino,Pardo,Não informado,Jaboatão dos Guararapes,PE,NaN,NaN,NaN,Educação Superior Completo,NaN,NaN,Ciências Exatas,BC10,Salesforce,lCWu2zPwrWCyIijGjS4c,DELOITTE,Formado,Empregado,NaN,NaN,NaN,False,Não informado,7.6,1978-02-21
1684,RAPHAEL PACHECO XAVIER,zv0TpnVdxDTObTc2Q8hw,696902400000,Masculino,Branco,NaN,RIO DE JANEIRO,RJ,NaN,NaN,NaN,Ensino Médio,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,NaN,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN,1992-02-01
1685,ALINE PACHECO MARTINS,zw56ykXNM5TEH54tSGG9,635628449069,Feminino,Branco,Casado,Porto Alegre,RS,NaN,NaN,NaN,Não informado,NaN,NaN,Não informado,BC01,Web Full Stack,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,Formado,Empregado,NaN,NaN,NaN,False,0,9.6,1990-02-21
1686,HUGO PEDRA GONÇALVES,zwWs8hZhd6zPGSflTm9S,761858849079,Masculino,Branco,Não informado,Rio de Janeiro,RJ,NaN,NaN,NaN,Mestrado,NaN,NaN,Ciências Exatas,BC08,Engenharia de Dados,koH17PebhftgjcWzxQFc,EXTERNO,Formado,Empregado,Wed Jun 08 2022 15:36:15 GMT+0000 (Coordinated...,Placement,VpXRjNf22MNy6oSLvh9jxF60dpC2,False,Não informado,8.6,1994-02-21
1687,VICTOR HUGO PAULA RODRIGUES,zy2F1KMsPkWLqNvUWvk6,978307200000,Masculino,Pardo,NaN,Uberlândia,MG,NaN,NaN,NaN,Mestrado,NaN,NaN,NaN,AD1,Analista de Dados,uyMEdf66N9WqSJ35XSP1,NaN,Cursando,Em Formação,NaN,NaN,NaN,False,NaN,NaN,2001-01-01

####Substituição de campos vazios

In [ ]:
#Reescreve os valores NA com NAO INFORMADO
for coluna in df.columns:
    if coluna != 'dataNascimentoTratada' and coluna != 'empregabilidadeLastUpdate' :
        df[coluna].fillna('NAO INFORMADO', inplace=True)

####Padronização de texto no df inteiro

In [ ]:
# função para padronizar textos
def padronizar_textos(texto):
    texto = texto.upper()  # deixar o texto em maiúsculo
    texto = unidecode.unidecode(texto)  # remover acentos
    return texto

# lista com o nome das colunas que não serão modificadas
colunas_nao_modificadas = ['nomeCompleto','id', 'dataNascimentoTratada',
                           'bootcampCodigo', 'empregabilidadeLastUpdate']

# aplicar a função somente nas colunas que não estão na lista 'colunas_nao_modificadas'
df.loc[:, ~df.columns.isin(colunas_nao_modificadas)] = (df.loc[:, ~df.columns.isin(colunas_nao_modificadas)]
                                                        .applymap(lambda x: padronizar_textos(x)
                                                         if isinstance(x, str) else x))
# Altera os campos da coluna 'nomeCompleto' para maiúsculas
df['nomeCompleto'] = df['nomeCompleto'].str.upper()

In [ ]:
df

,nomeCompleto,id,dataNascimento,genero,etnia,estadoCivil,cidade,uf,deficiencia,tipoDeficiencia,disponibilidadeMudanca,escolaridadeNivel,formacaoAcademica,nomeDoCursoSuperior,areaFormacao,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate,empregabilidadeUpdateBy.type,empregabilidadeUpdateBy.uid,favorito,filhos,mediaFinal,dataNascimentoTratada
0,FRANCELLOISE ANTUNES CARDOSO,01q3O0Z8RJyT0q7bdHZp,698700449074,FEMININO,BRANCO,NAO INFORMADO,CURITIBA,PR,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,EDUCACAO SUPERIOR COMPLETO,NAO INFORMADO,NAO INFORMADO,CIENCIAS HUMANAS E SOCIAIS,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,FORMADO,EMPREGADO,NaN,NAO INFORMADO,NAO INFORMADO,False,NAO INFORMADO,7,1992-02-21
1,WALLACE ALMEIDA VALERIANO,04oog90rzyRPyQdruFQQ,667164449077,MASCULINO,PARDO,SOLTEIRO,CUSTODIA,PE,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,EDUCACAO SUPERIOR INCOMPLETO,NAO INFORMADO,NAO INFORMADO,CIENCIAS EXATAS,BC06,ENGENHARIA DE DADOS,6FFmCn0K9rpi4p7iLAMK,EXTERNO,FORMADO,EMPREGADO,NaN,NAO INFORMADO,NAO INFORMADO,False,0,5.73,1991-02-21
2,MAGDA DANTAS SANTANA,08DFPlaZHy7EKM2iigsa,499737600000,FEMININO,PARDO,CASADA,SAO PAULO,SP,NAO,NAO INFORMADO,NAO INFORMADO,EDUCACAO SUPERIOR COMPLETO,CIENCIA DA COMPUTACAO,NAO INFORMADO,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaN,NAO INFORMADO,NAO INFORMADO,False,NAO INFORMADO,NAO INFORMADO,1985-11-02
3,DENER AUGUSTO DOS ANJOS OLIVEIRA,0BMulajtduVo1wT7yDsO,782438400000,MASCULINO,BRANCO,SOLTEIRO,SUMARE,SP,NAO,NAO INFORMADO,NAO INFORMADO,EDUCACAO SUPERIOR INCOMPLETO,ANALISE E DESENVOLVIMENTO DE SISTEMAS,NAO INFORMADO,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaN,NAO INFORMADO,NAO INFORMADO,False,NAO INFORMADO,NAO INFORMADO,1994-10-18
4,THOMAZ NOBUKI PEREIRA,0G9LjTAzN9GRdyBXUcxW,579225600000,MASCULINO,BRANCO,DIVORCIADO,OSASCO,SP,NAO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaN,NAO INFORMADO,NAO INFORMADO,False,NAO INFORMADO,NAO INFORMADO,1988-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,FÁBIO FERREIRA DOS SANTOS,zty1iQUdFZy0fIkk8cqZ,256931097982,MASCULINO,PARDO,NAO INFORMADO,JABOATAO DOS GUARARAPES,PE,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,EDUCACAO SUPERIOR COMPLETO,NAO INFORMADO,NAO INFORMADO,CIENCIAS EXATAS,BC10,SALESFORCE,lCWu2zPwrWCyIijGjS4c,DELOITTE,FORMADO,EMPREGADO,NaN,NAO INFORMADO,NAO INFORMADO,False,NAO INFORMADO,7.6,1978-02-21
1684,RAPHAEL PACHECO XAVIER,zv0TpnVdxDTObTc2Q8hw,696902400000,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,ENSINO MEDIO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaN,NAO INFORMADO,NAO INFORMADO,False,NAO INFORMADO,NAO INFORMADO,1992-02-01
1685,ALINE PACHECO MARTINS,zw56ykXNM5TEH54tSGG9,635628449069,FEMININO,BRANCO,CASADO,PORTO ALEGRE,RS,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,BC01,WEB FULL STACK,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,FORMADO,EMPREGADO,NaN,NAO INFORMADO,NAO INFORMADO,False,0,9.6,1990-02-21
1686,HUGO PEDRA GONÇALVES,zwWs8hZhd6zPGSflTm9S,761858849079,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,MESTRADO,NAO INFORMADO,NAO INFORMADO,CIENCIAS EXATAS,BC08,ENGENHARIA DE DADOS,koH17PebhftgjcWzxQFc,EXTERNO,FORMADO,EMPREGADO,Wed Jun 08 2022 15:36:15 GMT+0000 (Coordinated...,PLACEMENT,VPXRJNF22MNY6OSLVH9JXF60DPC2,False,NAO INFORMADO,8.6,1994-02-21
1687,VICTOR HUGO PAULA RODRIGUES,zy2F1KMsPkWLqNvUWvk6,978307200000,MASCULINO,PARDO,NAO INFORMADO,UBERLANDIA,MG,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,MESTRADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaN,NAO INFORMADO,NAO INFORMADO,False,NAO INFORMADO,NAO INFORMADO,2001-01-01

####Padronização de campos com o mesmo nome

In [ ]:
#Substituição de variantes
df['estadoCivil'] = df['estadoCivil'].replace({'CASADO': 'CASADO(A)', 'CASADA': 'CASADO(A)',
                                               'DIVORCIADO': 'DIVORCIADO(A)', 'DIVORCIADA': 'DIVORCIADO(A)',
                                               'SEPARADO': 'DIVORCIADO(A)', 'SOLTEIRO': 'SOLTEIRO(A)',
                                               'SOLTEIRA': 'SOLTEIRO(A)'})

df['escolaridadeNivel'] = (df['escolaridadeNivel'].replace({'EDUCACAO SUPERIOR COMPLETO': 'SUP. COMPLETO',
                                                            'EDUCACAO SUPERIOR INCOMPLETO': 'SUP. INCOMPLETO',
                                                            'SUPERIOR COMPLETO': 'SUP. COMPLETO', 
                                                            'SUPERIOR INCOMPLETO': 'SUP. INCOMPLETO',
                                                            'MEDIO COMPLETO': 'ENSINO MEDIO', 
                                                            'MEDIO INCOMPLETO': 'ENSINO MEDIO',
                                                            'ENSINO FUNDAMENTAL': 'OUTROS',
                                                            'ESPECIALISTA': 'ESPECIALIZACAO',
                                                            'MESTRADO': 'MESTRADO',
                                                            'MESTRADO COMPLETO': 'MESTRADO',
                                                            'POS-GRADUACAO COMPLETO': 'ESPECIALIZACAO',
                                                            'POS-GRADUACAO INCOMPLETO': 'ESPECIALIZACAO'}))

In [ ]:
df.groupby(['estadoCivil'], dropna=False).size().sort_values(ascending=False)

estadoCivil
NAO INFORMADO    1339
SOLTEIRO(A)       222
CASADO(A)         106
DIVORCIADO(A)      13
UNIAO ESTAVEL       8
dtype: int64

In [ ]:
df.groupby(['escolaridadeNivel'], dropna=False).size().sort_values(ascending=False)

escolaridadeNivel
SUP. COMPLETO      612
SUP. INCOMPLETO    460
ENSINO MEDIO       255
NAO INFORMADO      212
ESPECIALIZACAO      84
CURSO TECNICO       33
MESTRADO            30
DOUTORADO            1
OUTROS               1
dtype: int64

###Retirada de colunas

colunas que serão retiradas
* dataNascimento
* deficiencia
* tipoDeficiencia
* disponibilidadeMudanca
* formacaoAcademica
* nomeDoCursoSuperior
* empregabilidadeUpdateBy.type
* empregabilidadeUpdateBy.uid
* favorito
* filhos
* mediaFinal

motivo: não existem dados suficientes para a análise e alguns deles estão inconsistentes

In [ ]:
# Criando grupos de colunas relacionadas
grupo1 = ['id', 'nomeCompleto', 'dataNascimentoTratada', 'genero', 'etnia', 'estadoCivil', 'cidade', 'uf']
grupo2 = ['escolaridadeNivel']
grupo3 = ['bootcampNome', 'bootcampTipo', 'bootcampCodigo', 'parceiroAssociado', 'statusNoBootcamp']
grupo4 = ['statusEmpregabilidade', 'empregabilidadeLastUpdate']

In [ ]:
# Reordenando o dataframe com as colunas em grupos relacionados
df = df[grupo1 + grupo2 + grupo3 + grupo4]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1688 entries, 0 to 1687
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1688 non-null   object
 1   nomeCompleto               1688 non-null   object
 2   dataNascimentoTratada      1468 non-null   datetime64[ns]
 3   genero                     1688 non-null   object
 4   etnia                      1688 non-null   object
 5   estadoCivil                1688 non-null   object
 6   cidade                     1688 non-null   object
 7   uf                         1688 non-null   object
 8   escolaridadeNivel          1688 non-null   object
 9   bootcampNome               1688 non-null   object
 10  bootcampTipo               1688 non-null   object
 11  bootcampCodigo             1688 non-null   object
 12  parceiroAssociado          1688 non-null   object
 13  statusNoBootcamp           1688 non-null   object
 14  statusEmpregabilidade      1688 non-null   object
 15  empregabilidadeLastUpdate  392 non-null    object
dtypes: datetime64[ns](1), object(15)
memory usage: 211.1+ KB

In [ ]:
df.head(10)

,id,nomeCompleto,dataNascimentoTratada,genero,etnia,estadoCivil,cidade,uf,escolaridadeNivel,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate
0,01q3O0Z8RJyT0q7bdHZp,FRANCELLOISE ANTUNES CARDOSO,1992-02-21,FEMININO,BRANCO,NAO INFORMADO,CURITIBA,PR,SUP. COMPLETO,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,FORMADO,EMPREGADO,NaN
1,04oog90rzyRPyQdruFQQ,WALLACE ALMEIDA VALERIANO,1991-02-21,MASCULINO,PARDO,SOLTEIRO(A),CUSTODIA,PE,SUP. INCOMPLETO,BC06,ENGENHARIA DE DADOS,6FFmCn0K9rpi4p7iLAMK,EXTERNO,FORMADO,EMPREGADO,NaN
2,08DFPlaZHy7EKM2iigsa,MAGDA DANTAS SANTANA,1985-11-02,FEMININO,PARDO,CASADO(A),SAO PAULO,SP,SUP. COMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaN
3,0BMulajtduVo1wT7yDsO,DENER AUGUSTO DOS ANJOS OLIVEIRA,1994-10-18,MASCULINO,BRANCO,SOLTEIRO(A),SUMARE,SP,SUP. INCOMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaN
4,0G9LjTAzN9GRdyBXUcxW,THOMAZ NOBUKI PEREIRA,1988-05-10,MASCULINO,BRANCO,DIVORCIADO(A),OSASCO,SP,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaN
5,0JiTfs8sTTG2AvjYKw92,NICOLE CRISTINE DA SILVA COTA,1992-02-21,FEMININO,BRANCO,NAO INFORMADO,SAO PAULO,SP,SUP. COMPLETO,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,DELOITTE,FORMADO,EMPREGADO,NaN
6,0Jl51RAF0bFZM8jL3y60,LUCAS MENDES BARBOSA,NaT,MASCULINO,PARDO,NAO INFORMADO,NAO INFORMADO,RJ,NAO INFORMADO,BC21,SALESFORCE,7uVovxasalK3skKfgvTA,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaN
7,0P00UMBgptfYxy7TwS8p,EDUARDO SOARES PENIDO,1984-02-21,MASCULINO,BRANCO,NAO INFORMADO,BARRA MANSA,RJ,SUP. COMPLETO,BC08,ENGENHARIA DE DADOS,koH17PebhftgjcWzxQFc,EXTERNO,FORMADO,EMPREGADO,NaN
8,0QHE5Uitk48XdB0gewAq,JOËL VILTUS,1982-10-07,MASCULINO,PRETO,SOLTEIRO(A),CAMPINAS,SP,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,EVASAO,NAO EMPREGAVEL,NaN
9,0TDEOSdsCDuyLTSBSCC0,AMANDA DA SILVA RODRIGUES,1990-01-31,FEMININO,PARDO,NAO INFORMADO,SERRA NEGRA,SP,SUP. COMPLETO,BC25,WEB FULL STACK,mKI0NenT4UUfZ758N3WD,NAO INFORMADO,FORMADO,DISPONIVEL,Wed Mar 15 2023 10:25:53 GMT-0300 (Horário Pad...

###Correção coluna empregabilidadeLastUpdate para datetime

In [ ]:
#backup
df_backup = df.copy()

In [ ]:
#Sobrescreve com o backup
df = df_backup.copy()

In [ ]:
# Substituindo np.NaN por pd.NA somente na coluna 'empregabilidadeLastUpdate'
df.loc[:, 'empregabilidadeLastUpdate'] = df['empregabilidadeLastUpdate'].replace(np.NaN, pd.NA)

#Trocar valores ausentes por 'CONTROLE'
df['empregabilidadeLastUpdate'].fillna('CONTROLE', inplace=True)

#Converter a coluna inteira para string
df['empregabilidadeLastUpdate'] = df['empregabilidadeLastUpdate'].astype(str)

# Definir uma função para remover trechos de texto usando expressões regulares
def remover_trecho(texto):
    padrao = r"\s+\(.+\)$" #um ou mais espaços seguidos de parênteses e qualquer coisa dentro deles
    novo_texto = re.sub(padrao, "", texto) #substitui o trecho de texto pela string vazia
    return novo_texto

# Aplicar a função na coluna do dataframe
df['empregabilidadeLastUpdate'] = df['empregabilidadeLastUpdate'].apply(remover_trecho)

In [ ]:
df

,id,nomeCompleto,dataNascimentoTratada,genero,etnia,estadoCivil,cidade,uf,escolaridadeNivel,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate
0,01q3O0Z8RJyT0q7bdHZp,FRANCELLOISE ANTUNES CARDOSO,1992-02-21,FEMININO,BRANCO,NAO INFORMADO,CURITIBA,PR,SUP. COMPLETO,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,FORMADO,EMPREGADO,CONTROLE
1,04oog90rzyRPyQdruFQQ,WALLACE ALMEIDA VALERIANO,1991-02-21,MASCULINO,PARDO,SOLTEIRO(A),CUSTODIA,PE,SUP. INCOMPLETO,BC06,ENGENHARIA DE DADOS,6FFmCn0K9rpi4p7iLAMK,EXTERNO,FORMADO,EMPREGADO,CONTROLE
2,08DFPlaZHy7EKM2iigsa,MAGDA DANTAS SANTANA,1985-11-02,FEMININO,PARDO,CASADO(A),SAO PAULO,SP,SUP. COMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,CONTROLE
3,0BMulajtduVo1wT7yDsO,DENER AUGUSTO DOS ANJOS OLIVEIRA,1994-10-18,MASCULINO,BRANCO,SOLTEIRO(A),SUMARE,SP,SUP. INCOMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,CONTROLE
4,0G9LjTAzN9GRdyBXUcxW,THOMAZ NOBUKI PEREIRA,1988-05-10,MASCULINO,BRANCO,DIVORCIADO(A),OSASCO,SP,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,CONTROLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,zty1iQUdFZy0fIkk8cqZ,FÁBIO FERREIRA DOS SANTOS,1978-02-21,MASCULINO,PARDO,NAO INFORMADO,JABOATAO DOS GUARARAPES,PE,SUP. COMPLETO,BC10,SALESFORCE,lCWu2zPwrWCyIijGjS4c,DELOITTE,FORMADO,EMPREGADO,CONTROLE
1684,zv0TpnVdxDTObTc2Q8hw,RAPHAEL PACHECO XAVIER,1992-02-01,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,ENSINO MEDIO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,CONTROLE
1685,zw56ykXNM5TEH54tSGG9,ALINE PACHECO MARTINS,1990-02-21,FEMININO,BRANCO,CASADO(A),PORTO ALEGRE,RS,NAO INFORMADO,BC01,WEB FULL STACK,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,FORMADO,EMPREGADO,CONTROLE
1686,zwWs8hZhd6zPGSflTm9S,HUGO PEDRA GONÇALVES,1994-02-21,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,MESTRADO,BC08,ENGENHARIA DE DADOS,koH17PebhftgjcWzxQFc,EXTERNO,FORMADO,EMPREGADO,Wed Jun 08 2022 15:36:15 GMT+0000
1687,zy2F1KMsPkWLqNvUWvk6,VICTOR HUGO PAULA RODRIGUES,2001-01-01,MASCULINO,PARDO,NAO INFORMADO,UBERLANDIA,MG,MESTRADO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,CONTROLE

In [ ]:
for k, v in df.items():
    if k == 'empregabilidadeLastUpdate':
        v = v.astype(str)
        for i, row in v.items():
            if 'CONTROLE' not in row:
                data_string = str(row)
                data_formato = "%a %b %d %Y %H:%M:%S GMT%z"
                data_objeto = datetime.strptime(data_string, data_formato)
                df.at[i, k] = data_objeto.strftime("%Y-%m-%d %H:%M:%S")

In [ ]:
df

,id,nomeCompleto,dataNascimentoTratada,genero,etnia,estadoCivil,cidade,uf,escolaridadeNivel,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate
0,01q3O0Z8RJyT0q7bdHZp,FRANCELLOISE ANTUNES CARDOSO,1992-02-21,FEMININO,BRANCO,NAO INFORMADO,CURITIBA,PR,SUP. COMPLETO,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,FORMADO,EMPREGADO,CONTROLE
1,04oog90rzyRPyQdruFQQ,WALLACE ALMEIDA VALERIANO,1991-02-21,MASCULINO,PARDO,SOLTEIRO(A),CUSTODIA,PE,SUP. INCOMPLETO,BC06,ENGENHARIA DE DADOS,6FFmCn0K9rpi4p7iLAMK,EXTERNO,FORMADO,EMPREGADO,CONTROLE
2,08DFPlaZHy7EKM2iigsa,MAGDA DANTAS SANTANA,1985-11-02,FEMININO,PARDO,CASADO(A),SAO PAULO,SP,SUP. COMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,CONTROLE
3,0BMulajtduVo1wT7yDsO,DENER AUGUSTO DOS ANJOS OLIVEIRA,1994-10-18,MASCULINO,BRANCO,SOLTEIRO(A),SUMARE,SP,SUP. INCOMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,CONTROLE
4,0G9LjTAzN9GRdyBXUcxW,THOMAZ NOBUKI PEREIRA,1988-05-10,MASCULINO,BRANCO,DIVORCIADO(A),OSASCO,SP,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,CONTROLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,zty1iQUdFZy0fIkk8cqZ,FÁBIO FERREIRA DOS SANTOS,1978-02-21,MASCULINO,PARDO,NAO INFORMADO,JABOATAO DOS GUARARAPES,PE,SUP. COMPLETO,BC10,SALESFORCE,lCWu2zPwrWCyIijGjS4c,DELOITTE,FORMADO,EMPREGADO,CONTROLE
1684,zv0TpnVdxDTObTc2Q8hw,RAPHAEL PACHECO XAVIER,1992-02-01,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,ENSINO MEDIO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,CONTROLE
1685,zw56ykXNM5TEH54tSGG9,ALINE PACHECO MARTINS,1990-02-21,FEMININO,BRANCO,CASADO(A),PORTO ALEGRE,RS,NAO INFORMADO,BC01,WEB FULL STACK,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,FORMADO,EMPREGADO,CONTROLE
1686,zwWs8hZhd6zPGSflTm9S,HUGO PEDRA GONÇALVES,1994-02-21,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,MESTRADO,BC08,ENGENHARIA DE DADOS,koH17PebhftgjcWzxQFc,EXTERNO,FORMADO,EMPREGADO,2022-06-08 15:36:15
1687,zy2F1KMsPkWLqNvUWvk6,VICTOR HUGO PAULA RODRIGUES,2001-01-01,MASCULINO,PARDO,NAO INFORMADO,UBERLANDIA,MG,MESTRADO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,CONTROLE

In [ ]:
# Substituir os valores "CONTROLE" por pd.NaT
df['empregabilidadeLastUpdate'] = df['empregabilidadeLastUpdate'].replace('CONTROLE', pd.NaT)

# Converter a coluna para datetime
df['empregabilidadeLastUpdate'] = pd.to_datetime(df['empregabilidadeLastUpdate'])

In [ ]:
df

,id,nomeCompleto,dataNascimentoTratada,genero,etnia,estadoCivil,cidade,uf,escolaridadeNivel,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate
0,01q3O0Z8RJyT0q7bdHZp,FRANCELLOISE ANTUNES CARDOSO,1992-02-21,FEMININO,BRANCO,NAO INFORMADO,CURITIBA,PR,SUP. COMPLETO,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,FORMADO,EMPREGADO,NaT
1,04oog90rzyRPyQdruFQQ,WALLACE ALMEIDA VALERIANO,1991-02-21,MASCULINO,PARDO,SOLTEIRO(A),CUSTODIA,PE,SUP. INCOMPLETO,BC06,ENGENHARIA DE DADOS,6FFmCn0K9rpi4p7iLAMK,EXTERNO,FORMADO,EMPREGADO,NaT
2,08DFPlaZHy7EKM2iigsa,MAGDA DANTAS SANTANA,1985-11-02,FEMININO,PARDO,CASADO(A),SAO PAULO,SP,SUP. COMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT
3,0BMulajtduVo1wT7yDsO,DENER AUGUSTO DOS ANJOS OLIVEIRA,1994-10-18,MASCULINO,BRANCO,SOLTEIRO(A),SUMARE,SP,SUP. INCOMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT
4,0G9LjTAzN9GRdyBXUcxW,THOMAZ NOBUKI PEREIRA,1988-05-10,MASCULINO,BRANCO,DIVORCIADO(A),OSASCO,SP,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,zty1iQUdFZy0fIkk8cqZ,FÁBIO FERREIRA DOS SANTOS,1978-02-21,MASCULINO,PARDO,NAO INFORMADO,JABOATAO DOS GUARARAPES,PE,SUP. COMPLETO,BC10,SALESFORCE,lCWu2zPwrWCyIijGjS4c,DELOITTE,FORMADO,EMPREGADO,NaT
1684,zv0TpnVdxDTObTc2Q8hw,RAPHAEL PACHECO XAVIER,1992-02-01,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,ENSINO MEDIO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaT
1685,zw56ykXNM5TEH54tSGG9,ALINE PACHECO MARTINS,1990-02-21,FEMININO,BRANCO,CASADO(A),PORTO ALEGRE,RS,NAO INFORMADO,BC01,WEB FULL STACK,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,FORMADO,EMPREGADO,NaT
1686,zwWs8hZhd6zPGSflTm9S,HUGO PEDRA GONÇALVES,1994-02-21,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,MESTRADO,BC08,ENGENHARIA DE DADOS,koH17PebhftgjcWzxQFc,EXTERNO,FORMADO,EMPREGADO,2022-06-08 15:36:15
1687,zy2F1KMsPkWLqNvUWvk6,VICTOR HUGO PAULA RODRIGUES,2001-01-01,MASCULINO,PARDO,NAO INFORMADO,UBERLANDIA,MG,MESTRADO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaT

In [ ]:
df['empregabilidadeLastUpdate'] = pd.to_datetime(df['empregabilidadeLastUpdate'].dt.strftime('%Y-%m-%d'))

In [ ]:
df

,id,nomeCompleto,dataNascimentoTratada,genero,etnia,estadoCivil,cidade,uf,escolaridadeNivel,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate
0,01q3O0Z8RJyT0q7bdHZp,FRANCELLOISE ANTUNES CARDOSO,1992-02-21,FEMININO,BRANCO,NAO INFORMADO,CURITIBA,PR,SUP. COMPLETO,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,FORMADO,EMPREGADO,NaT
1,04oog90rzyRPyQdruFQQ,WALLACE ALMEIDA VALERIANO,1991-02-21,MASCULINO,PARDO,SOLTEIRO(A),CUSTODIA,PE,SUP. INCOMPLETO,BC06,ENGENHARIA DE DADOS,6FFmCn0K9rpi4p7iLAMK,EXTERNO,FORMADO,EMPREGADO,NaT
2,08DFPlaZHy7EKM2iigsa,MAGDA DANTAS SANTANA,1985-11-02,FEMININO,PARDO,CASADO(A),SAO PAULO,SP,SUP. COMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT
3,0BMulajtduVo1wT7yDsO,DENER AUGUSTO DOS ANJOS OLIVEIRA,1994-10-18,MASCULINO,BRANCO,SOLTEIRO(A),SUMARE,SP,SUP. INCOMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT
4,0G9LjTAzN9GRdyBXUcxW,THOMAZ NOBUKI PEREIRA,1988-05-10,MASCULINO,BRANCO,DIVORCIADO(A),OSASCO,SP,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,zty1iQUdFZy0fIkk8cqZ,FÁBIO FERREIRA DOS SANTOS,1978-02-21,MASCULINO,PARDO,NAO INFORMADO,JABOATAO DOS GUARARAPES,PE,SUP. COMPLETO,BC10,SALESFORCE,lCWu2zPwrWCyIijGjS4c,DELOITTE,FORMADO,EMPREGADO,NaT
1684,zv0TpnVdxDTObTc2Q8hw,RAPHAEL PACHECO XAVIER,1992-02-01,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,ENSINO MEDIO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaT
1685,zw56ykXNM5TEH54tSGG9,ALINE PACHECO MARTINS,1990-02-21,FEMININO,BRANCO,CASADO(A),PORTO ALEGRE,RS,NAO INFORMADO,BC01,WEB FULL STACK,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,FORMADO,EMPREGADO,NaT
1686,zwWs8hZhd6zPGSflTm9S,HUGO PEDRA GONÇALVES,1994-02-21,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,MESTRADO,BC08,ENGENHARIA DE DADOS,koH17PebhftgjcWzxQFc,EXTERNO,FORMADO,EMPREGADO,2022-06-08
1687,zy2F1KMsPkWLqNvUWvk6,VICTOR HUGO PAULA RODRIGUES,2001-01-01,MASCULINO,PARDO,NAO INFORMADO,UBERLANDIA,MG,MESTRADO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaT

###Realizando o merge da culuna dataTermino do df_turmas para o df (estudantes) esta data é importante para o datavis no Looker Studio e no PowerBi

In [ ]:
df_estudantes_merged = pd.merge(df, df_turmas[['bootcampCodigo', 'dataTermino']], on='bootcampCodigo', how='left')

In [ ]:
df_estudantes_merged

,id,nomeCompleto,dataNascimentoTratada,genero,etnia,estadoCivil,cidade,uf,escolaridadeNivel,bootcampNome,bootcampTipo,bootcampCodigo,parceiroAssociado,statusNoBootcamp,statusEmpregabilidade,empregabilidadeLastUpdate,dataTermino
0,01q3O0Z8RJyT0q7bdHZp,FRANCELLOISE ANTUNES CARDOSO,1992-02-21,FEMININO,BRANCO,NAO INFORMADO,CURITIBA,PR,SUP. COMPLETO,BC04,GOOGLE CLOUD COMPUTING,hzymD9j5KwP9r4Ae33t3,GLOBAL HITSS,FORMADO,EMPREGADO,NaT,2021-08-12
1,04oog90rzyRPyQdruFQQ,WALLACE ALMEIDA VALERIANO,1991-02-21,MASCULINO,PARDO,SOLTEIRO(A),CUSTODIA,PE,SUP. INCOMPLETO,BC06,ENGENHARIA DE DADOS,6FFmCn0K9rpi4p7iLAMK,EXTERNO,FORMADO,EMPREGADO,NaT,2021-12-03
2,08DFPlaZHy7EKM2iigsa,MAGDA DANTAS SANTANA,1985-11-02,FEMININO,PARDO,CASADO(A),SAO PAULO,SP,SUP. COMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT,2022-10-03
3,0BMulajtduVo1wT7yDsO,DENER AUGUSTO DOS ANJOS OLIVEIRA,1994-10-18,MASCULINO,BRANCO,SOLTEIRO(A),SUMARE,SP,SUP. INCOMPLETO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT,2022-10-03
4,0G9LjTAzN9GRdyBXUcxW,THOMAZ NOBUKI PEREIRA,1988-05-10,MASCULINO,BRANCO,DIVORCIADO(A),OSASCO,SP,NAO INFORMADO,BC24,SALESFORCE,OvL1dam3Yy4IzlgP4TJm,NAO INFORMADO,DESISTENTE,NAO EMPREGAVEL,NaT,2022-10-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,zty1iQUdFZy0fIkk8cqZ,FÁBIO FERREIRA DOS SANTOS,1978-02-21,MASCULINO,PARDO,NAO INFORMADO,JABOATAO DOS GUARARAPES,PE,SUP. COMPLETO,BC10,SALESFORCE,lCWu2zPwrWCyIijGjS4c,DELOITTE,FORMADO,EMPREGADO,NaT,2022-02-25
1684,zv0TpnVdxDTObTc2Q8hw,RAPHAEL PACHECO XAVIER,1992-02-01,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,ENSINO MEDIO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaT,2023-05-18
1685,zw56ykXNM5TEH54tSGG9,ALINE PACHECO MARTINS,1990-02-21,FEMININO,BRANCO,CASADO(A),PORTO ALEGRE,RS,NAO INFORMADO,BC01,WEB FULL STACK,hx5dHDdRlX6q1LAysknt,GLOBAL HITSS,FORMADO,EMPREGADO,NaT,2021-05-31
1686,zwWs8hZhd6zPGSflTm9S,HUGO PEDRA GONÇALVES,1994-02-21,MASCULINO,BRANCO,NAO INFORMADO,RIO DE JANEIRO,RJ,MESTRADO,BC08,ENGENHARIA DE DADOS,koH17PebhftgjcWzxQFc,EXTERNO,FORMADO,EMPREGADO,2022-06-08,2022-01-28
1687,zy2F1KMsPkWLqNvUWvk6,VICTOR HUGO PAULA RODRIGUES,2001-01-01,MASCULINO,PARDO,NAO INFORMADO,UBERLANDIA,MG,MESTRADO,AD1,ANALISTA DE DADOS,uyMEdf66N9WqSJ35XSP1,NAO INFORMADO,CURSANDO,EM FORMACAO,NaT,2023-05-18

### Carregando DataFrame Estudantes no Bucket do Projeto

In [ ]:
df_estudantes_merged.to_csv('gs://proj11/tratados/estudantes.csv',index=False)

##Bucket GCP - BigQuery

In [ ]:
# Criando um cliente para acessar o BigQuery
project_id = 'versatile-cove-384013'
bq_client = bigquery.Client(project=project_id)

# Criando um cliente para acessar o GCS
storage_client = storage.Client(project=project_id)

In [ ]:
# cria função para verificar se a tabela já existe no BigQuery e a exclui
def verifica_tabela(table_ref):
  try:
      bq_client.get_table(table_ref)
      bq_client.delete_table(table_ref)
      print(f"Tabela {table_name} excluída.")
  except Exception as e:
      print(f"Tabela {table_name} não existe. Criando a tabela no Big Query.")

In [ ]:
bucket_name = 'proj11'
dataset_id = 'soulcode'
table_name = 'estudantes'

# Referência ao bucket
bucket = storage_client.bucket(bucket_name)

# Carrega o arquivo do bucket para o BigQuery
dataset_ref = bq_client.dataset(dataset_id)
table_ref = dataset_ref.table(table_name)

# Consulta no BigQuery se a tabela já existe e a exclui, para evitar erro na execução
verifica_tabela(table_ref)

job_config = bigquery.LoadJobConfig()
job_config.source_format = bigquery.SourceFormat.CSV
job_config.skip_leading_rows = 1
job_config.autodetect = True
load_job = bq_client.load_table_from_uri('gs://proj11/tratados/estudantes.csv', table_ref, job_config=job_config)

# Aguarda a conclusão da carga da tabela
load_job.result()

Tabela estudantes excluída.

LoadJob<project=versatile-cove-384013, location=US, id=c5b4b62b-39d7-45fa-b490-39737b872d97>

In [ ]:
table_name = 'turmas'

# Carrega o arquivo do bucket para o BigQuery
dataset_ref = bq_client.dataset(dataset_id)
table_ref = dataset_ref.table(table_name)

# Consulta no BigQuery se a tabela já existe e a exclui, para evitar erro na execução
verifica_tabela(table_ref)

job_config = bigquery.LoadJobConfig()
job_config.source_format = bigquery.SourceFormat.CSV
job_config.skip_leading_rows = 1
job_config.autodetect = True
load_job = bq_client.load_table_from_uri('gs://proj11/tratados/turmas.csv', table_ref, job_config=job_config)

# Aguarda a conclusão da carga da tabela
load_job.result()

Tabela turmas excluída.

LoadJob<project=versatile-cove-384013, location=US, id=5a3d730b-e920-41a6-9d24-3e78d3434fc3>

In [ ]:
table_name = 'disciplinas'

# Carrega o arquivo do bucket para o BigQuery
dataset_ref = bq_client.dataset(dataset_id)
table_ref = dataset_ref.table(table_name)

# Consulta no BigQuery se a tabela já existe e a exclui, para evitar erro na execução
verifica_tabela(table_ref)

job_config = bigquery.LoadJobConfig()
job_config.source_format = bigquery.SourceFormat.CSV
job_config.skip_leading_rows = 1
job_config.autodetect = True
load_job = bq_client.load_table_from_uri('gs://proj11/tratados/disciplinas.csv', table_ref, job_config=job_config)

# Aguarda a conclusão da carga da tabela
load_job.result()

Tabela disciplinas excluída.

LoadJob<project=versatile-cove-384013, location=US, id=4c34e41a-c83f-401d-93d2-f4f7db567c34>

In [ ]:
table_name = 'professores'

# Carrega o arquivo do bucket para o BigQuery
dataset_ref = bq_client.dataset(dataset_id)
table_ref = dataset_ref.table(table_name)

# Consulta no BigQuery se a tabela já existe e a exclui, para evitar erro na execução
verifica_tabela(table_ref)

job_config = bigquery.LoadJobConfig()
job_config.source_format = bigquery.SourceFormat.CSV
job_config.skip_leading_rows = 1
job_config.autodetect = True
load_job = bq_client.load_table_from_uri('gs://proj11/tratados/professores.csv', table_ref, job_config=job_config)

# Aguarda a conclusão da carga da tabela
load_job.result()

Tabela professores excluída.

LoadJob<project=versatile-cove-384013, location=US, id=c4ca1cd6-a643-43e9-8d88-022ea815e4a8>